### ISSUE TITLE
Enhance metadata for sample-based datasets

### ISSUE THREAD

**Issue by wouteraddink** [gbif/ipt#1206]
For sample based datasets it would be nice to be able to add rich metadata: to include images or a PDF decribing a plot layout for example.

**Comment by kbraak** [comment]
Thanks for submitting this feature request. 

You are resurrecting a similar issue (#971) was that was raised in May 2013. I agree with you it would be really helpful when describing sample-based datasets. 

While this issue is under consideration, publishers should continue to include external links to such resources in their metadata. They can also be added to the data about the sampling event using [dcterms:references](http://rs.tdwg.org/dwc/terms/#dcterms:references).

**Comment by peterdesmet** [comment]
Or for describing a plot layout specifically, one can use `dwc:samplingProtocol`.

**Comment by DimEvil** [comment]
I don't understand why this is only about sample-based datasets.  Rich metadata is good for all datasets....
