### ISSUE TITLE
Concatenate line breaks for DCAT

### ISSUE THREAD

**Issue by peterdesmet** [gbif/ipt#1231]
In the DCAT feed, the turtle format requires line breaks to be escaped. This can be done in two ways, see https://github.com/LifeWatchINBO/ipt-dcat/issues/58#issuecomment-158429424

This currently happens for the dataset **description**, which accepts multiple paragraphs. I believe it is the only field that allows multiple paragraphs(?), line breaks in other text fields are already collapsed.

Can this be included in `milestone 2.3.3`?

Thanks!

**Comment by mkrbins** [comment]
This will be really nice when solved.
Am also using CKAN - DCAT extention.

**Comment by kbraak** [comment]
Issue fixed. It will be included in 2.3.3 release. Closing issue.

**Comment by kbraak** [comment]
Issue verified.

**Comment by peterdesmet** [comment]
We have IPT version `2.3.3-rdb4ab13` and it looks like this issue is not resolved. If you search for "indigenous plants in Flanders" in http://data.inbo.be/ipt/dcat, you'll notice that the line breaks are still present.

Note that there might be a difference between a linebreak character in a single paragraph and (the case above) multiple paragraphs (`<para>` in the EML). Maybe the first case is resolved with 90ef98f9026daffac03a90d2b2bec314f7834a35, but not the second case. Both cases should not cause linebreaks in dcat.

**Comment by kbraak** [comment]
@peterdesmet 

http://data.inbo.be/ipt/ still uses IPT Version 2.3.2-rea67259. I confirmed again that this issue been fixed in 2.3.3 while preparing the 2.3.4 release - needed to fix a Struts2 security vulnerability. As you may have noticed, your [recently contributed pull request](https://github.com/gbif/ipt/pull/1315) will be included in this release because you made it effortless to incorporate.

![screen shot 2017-03-10 at 09 51 11](https://cloud.githubusercontent.com/assets/5981100/23788714/1813080c-0578-11e7-8706-5fc41888cd2c.png)

**Comment by peterdesmet** [comment]
Ah, my mistake. Will verify again once we've updated to 2.3.4 😊

**Comment by peterdesmet** [comment]
Is indeed fixed. Multiple paragraphs are concatenated with `\n`. Line breaks in one description field are not escaped, but we can work around that.
