### ISSUE TITLE
Versioning darwin core / meta.xml

### ISSUE THREAD

**Issue by dvdscripter** [gbif/ipt#1233]
Hi,

I'm not sure if DWC standard enforce use of xml but when generating meta.xml (at IPT) no version of DWC is available at any place.

Can you place any validation/schema like eml?
```
xsi:schemaLocation="eml://ecoinformatics.org/eml-2.1.1
```

For developers trying to write indexers or custom validators you basically lost in which version of DWC the resource is made.

A similar issue is open at https://github.com/tdwg/dwc/issues/107

**Comment by kbraak** [comment]
Thank you for reporting this issue. I'm glad you also reported it in the [DwC project](https://github.com/tdwg/dwc/), because this is the appropriate place for it.

Please note that it is the IPT administrator's responsibility to keep their extensions up-to-date. This will guarantee that the IPT publishes using the latest DwC terms. Please refer to [this section](https://github.com/gbif/ipt/wiki/IPT2ManualNotes.wiki#update-extension) in the IPT User Manual for more information about how to update extensions.
