### ISSUE TITLE
Validator fails validating occurrence ext. of event core

### ISSUE THREAD

**Issue by meliezer** [gbif/ipt#1244]
Hello,
After the validator logs that all is ok (event id) it checks if takes the ID field from occurrenceID and of course fails. I get "Duplicate id found: Acanthoica quattrospina-urn:lsid:marinespecies.org:taxname:235802-absent".
(Always the same ID)
In the mapping GUI I do see correct samples for event and occurrenceID.

More log lines:
Validating the extension file: occurrence.txt. Depending on the number of records, this can take a while.
? Validating the basisOfRecord in the occurrence extension data file is always present and its value matches the Darwin Core Type Vocabulary.
? Validating the occurrenceId in occurrence extension data file is always present and unique. 
? Validating the ID field eventID is always present in extension data file. 
Duplicate id found: Acanthoica quattrospina-urn:lsid:marinespecies.org:taxname:235802-absent

IPT 2.3.1.

Regards,
Menashè

**Comment by kbraak** [comment]
Thanks for reporting this issue.

Please note that when the IPT validates occurrence records associated to event records (e.g. when the occurrence core is used an extension to the event core), it validates that each occurrence record has an eventID, and if occurrenceID is mapped, that the occurrenceID is unique. 

Using the above information, can you please verify that you have separate columns for eventID and occurrenceID for each occurrence record, that these columns are mapped properly, and that the occurrenceIDs are in fact unique? If this is the case, please send me your occurrence source file so that I can try to reproduce your error. Thanks

**Comment by meliezer** [comment]
Thank you Kyle for your response. It's my first attempt to use the occurrence extension.
I believe that it would be fine. If not, the issue would be different, so I'm closing this issue.

**Comment by kbraak** [comment]
Thanks, good to know.
