### ISSUE TITLE
Source filename use whitelist to validate ASCII input

### ISSUE THREAD

**Issue by dvdscripter** [gbif/ipt#1258]
Not sure if this a bug or feature request but when adding sources on resources and trying to use latin character IPT will complain.
`Source filename is invalid: filenames may only contain alpha-numeric characters (A-Z, 0-9), spaces, underscores, periods, parentheses, and hyphens.`
Which is correct description of allowed subsets, can IPT allow UTF-8 input? Checking https://en.wikipedia.org/wiki/Filename#Reserved_characters_and_words seems we still want some use of whitelist because is hard to guess OS limitations/interpretations of characters.

**Comment by kbraak** [comment]
The characters that can be used in the source name and the resource shortname (see issue #1253) are severely restricted already to be clear of OS limitations.

A bug would be, if the IPT permits you to save a source with a name that isn't persisted properly on your OS, or displayed improperly in the IPT user interface.

Otherwise, please just limit your source names to use the restricted set of characters the IPT defines, and try to upload them again. Thanks.
