### ISSUE TITLE
Web form elements missing from Darwin Core Identification History mapping interface

### ISSUE THREAD

**Issue by dshorthouse** [gbif/ipt#1265]
Upon upgrading an old resource to 2.3.2 that has existing Darwin Core Identification History data mapped, the mapping interface for this extension is visually truncated (all mappings + save/delete/back buttons) with the exception of occurrenceID and filter are not visible), but these are all apparently present in the DOM. It seems terms discovered to be "redundant" (also present in the core) is preventing the display of these terms & it is unclear what would happen if this resource were now republished. Are we now expected to put identification history in the occurrence core? If so, this a significant mistake, imho and will be exceptionally difficult to do now that we already have a workflow that retains these 1:many relations in an extension.

**Comment by kbraak** [comment]
Hi David, 

I suspect I know what the problem is. Click the "Show all classes" filter in the sidebar. Hiding redundant classes is a feature added in v2.3. More information about the new filters on the mapping page can be found here: https://github.com/gbif/ipt/wiki/IPT2ManualNotes.wiki#data-mapping-detail-page 

Please open a new issue, if you'd like to suggest an enhancement to this feature. I understand it is more bothersome to you than beneficial with this extension. Thanks.

**Comment by dshorthouse** [comment]
D'oh! Apologies; turns out it was my own css/js/ftl customizations that caused my inability to show/hide these redundant mappings. I elected to not show the sidebar and as a consequence, this option was not visible to me. I'll know better next time...
