### ISSUE TITLE
Unable to assert copyright holder along with licence in eml intellectualRights.

### ISSUE THREAD

**Issue by chicoreus** [gbif/ipt#1270]
In IPT the eml block intellectualRights is populated by a value selected from the Data License picklist.  This populates intellectualRights only with the licence text, and not, for the CC-BY or CC-BY-SA licences, who the copyright owner is that is granting the licence, that is the BY clause of these creative commons licenses.  The eml-2.1.1 schema example for the intellectualRights element clearly indicates that both the rights holder and the license are appropriate elements to include in the free text of the intellectualRights element: `<doc:example>Copyright``2001 Regents of the University of California Santa Barbara.  Free for use by all individuals provided that the owners are acknowledged in any use or publication.</doc:example>`.  EML is not as expressive here as Dublin Core, which allows separate specification of dcterms:rightsHolder (Regents of UCSD) and dcterms:licence (free for use as long as owners are acknowleged).   Citation does not appear to be the appropriate place to put a statement "Copyright © {year} {rightsHolder}, as citation in the EML documentation and in the DataCite preferred citation format implies a literature citation, not a copyright ownership assertion.

I would expect to be able to assert as eml:intellectualRights "Copyright © {year} {rightsHolder}, Some Rights Reserved.  This work is licensed under a Creative Commons Attribution Non Commercial (CC-BY-NC) 4.0 License.", and am required by my institution to assert the copyright statement.

An appropriate solution could involve adding dcterms:rightsHolder and dcterms:licence to the additionalMetadata block (which is defined in EML so as to allow the inclusion of terms from other vocabularies), and generating the eml:intellectualRights block from the content of those two terms.  This would allow picklist enforcement of the dcterms:licence, free text for the dcterms:rightsHolder, persistence of these terms independently, and construction of an appropriate eml:intellectualRights block that is not editable through the IPT user interface.

A workaround is to select the desired licence for a resource in IPT, shutdown the servelet container, edit the {ipt_data}/resources/{resourcename}/eml.xml file to add the copyright statement to the licence text in the intellectualRights block, restart the servlet container, and publish the resource.

Seen in both ipt-2.3.3-SNAPSHOT-r1a3e432 and ipt-2.3.2-rea67259.

**Comment by kbraak** [comment]
Thank you for submitting this issue Paul. I’m glad you found a workaround.
 
GBIF treats the rights holder as being equal to the publisher. When registering the dataset with GBIF, the publisher must agree that they have "made the necessary agreements with the original owners of the data that it can make the data available through the GBIF network”. This is a provision in the [GBIF Data Sharing Agreement](http://www.gbif.org/terms/licences/data-sharing), which will also be included in a new Data Publisher Agreement that will soon replace the Data Sharing Agreement to take account of the updated licensing arrangements in GBIF.org.
 
Based on the above, there is no possibility for a free text description of the rights holder. Based on your comments though, I agree it would be a nice improvement to explicitly show the publisher as the rights holder inside the intellectualRights license statement in order to help users satisfy Creative Commons' attribution requirements. See below for my proposal of how this change looks. 
 
I don’t want to put rights information in two places in the metadata document (e.g. in intellectualRights and dcterms:rightsHolder) because this will make it harder to read/more open to misinterpretation. Also I want to avoid using the term copyright holder. [GBIF’s stance](http://www.gbif.org/terms/licences) is that primary species occurrence data cannot be copyrighted because there is very little creative content in it, and most of it is made up of facts.

---
Below is a detailed description of proposed change to license text inside intellectualRights:

The default license statement inside intellectualRights for CC-BY v4.0 is:

"This work is licensed under a [Creative Commons Attribution (CC-BY) 4.0 License](http://creativecommons.org/licenses/by/4.0/legalcode)".

This is the same statement recommended by Creative Commons for applying the CC-BY 4.0 license [here](https://creativecommons.org/choose/results-one?license_code=by&amp;jurisdiction=&amp;version=4.0&amp;lang=en). 

As this issue highlights, the rights holder is not explicitly mentioned on the IPT dataset page or in the dataset's metadata document. 

To fix this, we could explicitly state that the rights holder is equal to the publishing organisation in the license text (for CC-BY and CC-BY-NC) like so:

"The rights holder of this work is [the publishing organisation]. This work is licensed under a [Creative Commons Attribution (CC-BY) 4.0 License](http://creativecommons.org/licenses/by/4.0/legalcode)".

**Comment by kbraak** [comment]
Version 2.3.3 will assert the rights holder along with the license on the resource homepage. An example of how the rights section of the resource homepage looks following this change is shown below. Note the text has only been highlighted to show the text that has been added. The final version won't actually highlight the text.

![screen shot 2016-11-01 at 11 56 40](https://cloud.githubusercontent.com/assets/5981100/19887701/50a1e3ea-a02a-11e6-9061-b923528f4372.png)

**Comment by kbraak** [comment]
Issue verified.

**Comment by kbraak** [comment]
Update to user manual completed. Change made in description of publishing organisation in this section of manual: https://github.com/gbif/ipt/wiki/IPT2ManualNotes.wiki#basic-metadata
