### ISSUE TITLE
IPT resource version number is not monotonic

### ISSUE THREAD

**Issue by godfoder** [gbif/ipt#1273]
This is a report against an IPT instance running version 2.1.1-r4640, if this issue is no longer present in later IPT versions, feel free to close.

iDigBio is observing a case where an IPT instance published a resource several times (for example, creating up to version 6). They then rolled the resource back to an older version (version 4). When they subsequently went to publish a new version, IPT called it version 5. This obviously invalidates the previous version 5, and breaks the chain to the old version 6, but there is no additional metadata to indicate that this happened.

iDigBio doesn't rely on this version number incrementing properly for our versioning, but others might and it is worth looking at seeing if there are other numbering paradigms that could provide this property. Perhaps a rollback could cause the next publish event to create a new major version?

**Comment by kbraak** [comment]
Thank you for reporting this issue. Can you please explain how exactly they "rolled the resource back to an older version?" Thanks.

**Comment by godfoder** [comment]
Basically:
http://collections.mnhn.fr/ipt/resource.do?r=mnhn-p&v=22, published 2015-12-10 (dated as last seen by iDigBio)
http://collections.mnhn.fr/ipt/resource.do?r=mnhn-p&v=21, published 2016-04-18 (not archived, but metadata indicates an original pub date of 2015-12-10)
http://collections.mnhn.fr/ipt/resource.do?r=mnhn-p&v=20, published 2016-04-20 (last seen dated, 2015-06-05)
http://collections.mnhn.fr/ipt/resource.do?r=mnhn-p&v=19, published 2016-04-19 (not archived, but metadata indicates an original pub date of 2015-06-05)
http://collections.mnhn.fr/ipt/resource.do?r=mnhn-p&v=18, published 2014-12-14

This has changed since this morning, but yesterday the "latest version" (as displayed by IPT) of mnhn-p was v18. This morning it was observed to be v19. and now its v20. If this rollback functionality isn't actually built into IPT, then this might be caused my manual editing of the filesystem, in which case you can close this bug.

If you'd like to view iDigBio's archived datasets, they are available at https://s.idigbio.org/idigbio-datasets-prod/<etag>

Our dataset history for this recordset is:

id | url | etag | modified
-- | --- | ---- | ---------
20738144 | http://api.idigbio.org/v1/recordsets/616857b7-f952-44ef-9b6f-576dc1e65b51 | 626a870516ee97d27ef59ee76c1de911 | 2016-04-20 12:23:59.299175
 20574469 | http://api.idigbio.org/v1/recordsets/616857b7-f952-44ef-9b6f-576dc1e65b51 | 01756e7fd05187ef80ee2c427fd4c8aa | 2016-04-19 05:22:38.042744
 20470710 | http://api.idigbio.org/v1/recordsets/616857b7-f952-44ef-9b6f-576dc1e65b51 | 2602f4626fcbd127140e6416e1c37bb4 | 2016-04-18 05:23:31.705763
 20470683 | http://api.idigbio.org/v1/recordsets/616857b7-f952-44ef-9b6f-576dc1e65b51 | f4e01c164351d5bf941ed6386932ed9a | 2016-04-18 04:23:15.368296
 12829138 | http://api.idigbio.org/v1/recordsets/616857b7-f952-44ef-9b6f-576dc1e65b51 | e4a114ed431ca20d7a4c31eee83259e3 | 2015-12-10 10:31:35.788432
  9839877 | http://api.idigbio.org/v1/recordsets/616857b7-f952-44ef-9b6f-576dc1e65b51 | e6089637329b4dd0fda8eda85f73a136 | 2015-07-15 11:16:07.249611

**Comment by kbraak** [comment]
Thanks Alex. Rollbacks aren't supported therefore this problem sounds like it is due to manual editing of the filesystem, which isn't condoned by the way ;) 

I'd like to encourage you to upgrade this IPT to the latest version 2.3.2. You'll notice the IPT moves to a new [versioning policy](https://github.com/gbif/ipt/wiki/IPT2Versioning.wiki) that supports major and minor versioning. Note the IPT must be configured with a DataCite or EZID account to assign DOIs to datasets corresponding with bumping major version numbers. 

Another change you'll notice during publication, is that the publisher is encouraged to enter a detailed summary of what has changed since the last publication. The change summary helps users track changes to the dataset over time. Here's [an example](http://cloud.gbif.org/eubon/resource?r=butterflies-monitoring-scheme-il#versions) of how it gets shown on the dataset homepage.
