### ISSUE TITLE
alternate domain/base URL for DOIs

### ISSUE THREAD

**Issue by bbrunet** [gbif/ipt#1278]
The IPT manual indicates that DOIs must be registered under the IPT's domain/base URL, otherwise registration via the IPT won't work. Sure enough when we attempted to register a DOI via our IPT overnight, we received the following error (domain of URL is not allowed), because we have a different domain registered with DataCite. This is because we intend on registering DOIs to non-IPT as well as IPT resources, and want to use a single domain for all our DOIs. It would be great if an alternate domain/base URL could be specified so that all DOIs registered using our IPT resolve to the same domain as our non-IPT resources.

Thanks,
Bryan

**Comment by kbraak** [comment]
Thanks Bryan, 

DataCite allows multiple host domains  to be assigned to your account. The easiest solution would be to ask your DataCite allocator to add your IPT's domain to your account. 

Alternatively, you could move your IPT's URL under the single domain currently assigned to your account. 

Looking forward to hearing what solution you choose.

**Comment by bbrunet** [comment]
Hi Kyle,

Thanks for the suggestions!

Unfortunately, we're unable to move the IPT's URL under our museum's domain since internal rules within our university require the use of a content management system for URLs under that domain. 

I ended up adding the IPT domain to our DataCite account yesterday, and have since registered DOIs for all our zoology collections. This should do for the meantime, however, I'm still not satisfied with this configuration since it will still result in DOIs for our biological collections resolving to a different domain than our other science/arts collections.

Bryan

**Comment by dshorthouse** [comment]
Bryan -
Could you hack a "fix" by grabbing, editing, and resubmitting the XML directly thru your DataCite account? This assumes you aren't regenerating new DOIs with every major publication event in your IPT. And, it also assumes that the non-IPT HTML landing pages you want the DOI to point to contains all that is necessary for a user to retrieve all the data (ie isn't just a cosmetic landing page).

**Comment by bbrunet** [comment]
Hi David,
Yes, I suppose I could do that. I have actually been playing around with the E2DCX (eml to DataCite XML) conversion tool on the Canadensys github page so that could work. And yes, our non-IPT landing pages are getting reworked to include all the necessary metadata.

Still though, it would be nice to be able to use the IPT with full DOI integration without such a hack to have DOIs resolve to non-IPT landing pages.

**Comment by kbraak** [comment]
Hi Bryan,

To satisfy the terms of your DataCite account, the landing page must provide:
* Information about the data. At a minimum this should cover the core metadata elements as defined by the [DataCite Metadata Schema](https://schema.datacite.org/) 
* Permanent (direct) access to the data and metadata or information about how to access it

The IPT satisfies these terms automatically for you. In addition, the IPT also enhances the comprehensibility and usability of the dataset by including the following things on the landing page:
* A version history table listing all major and minor versions so that changes can be easily tracked and each published version is easily accessible (note the [IPT's dataset versioning policy](https://github.com/gbif/ipt/wiki/IPT2Versioning.wiki) is based on DataCite's recommendations).
* Comprehensive metadata based on the [GBIF Metadata Profile based on EML](http://rs.gbif.org/schema/eml-gbif-profile/1.1/) including:
  * Information about how users can cite the dataset (note the [IPT's auto-generated citation format](https://github.com/gbif/ipt/wiki/IPT2Citation.wiki) includes the version number, is based on DataCite’s preferred citation format and satisfies the Joint Declaration of Data Citation Principles)
  * Information about how users can respect the license applied to the dataset (note in accordance with the [GBIF licensing policy](http://www.gbif.org/terms/licences), the IPT makes a dataset available for use under CC0, CC-BY, or CC-BY-NC).
* An indication if the dataset has been replaced by a newer version to promote use of the latest version
* An indication if the dataset has been removed 

Assuming the IPT allowed you to enter a custom dataset landing page URL for each DOI, the manager would have the additional burden of producing and updating these pages with changes (e.g. each time the dataset title or description changes). The IPT cannot guarantee the synchronicity of its landing page with the custom landing page, leading to inevitable inconsistencies that could lead to misuse or misinterpretation of the data. 

Therefore I would encourage you to weigh the pros and cons of making your own dataset landing pages. Not only will it be a lot more work, you will need to be careful to comply with the terms of your DataCite account otherwise DataCite can revoke your account.

**Comment by bbrunet** [comment]
Hi Kyle,

Your comment that the "the manager would have the additional burden of producing and updating these pages with changes" is definitely something I've been grappling with, and ultimately I think you're correct in positing that the increased opportunity for inconsistencies leading to misuse or misinterpretation grossly outweigh the pros of having non-IPT landing pages for IPT resources. 

My interest in creating non-IPT landing pages was purely out of a desire to have standardized landing page formats across all our collections, but alas you've convinced me that its not worth the effort. I agree that this would most likely amount to a lot of extra work without a method for automating the process and maintaining synchronicity. Having different landing pages for our non-IPT resources is a minor hiccup in my opinion. 

Thanks for the discussion!

Cheers,
Bryan

**Comment by kbraak** [comment]
You're welcome Bryan. Thanks for bringing this concern forward.

Although it can be a hindrance when updating your IPT, it is possible to [customize the IPT's style](https://github.com/gbif/ipt/wiki/IPT2Customization.wiki). Perhaps you could even just customize the landing page to bring it more in line with the other collections' landing pages. 

Alternatively, the open issue #1005 proposes to allow some customisation via the interface itself. If you think it's a good idea, please +1 or provide additional comments - thanks.
