### ISSUE TITLE
Required DwC fields - Occurrence Data

### ISSUE THREAD

**Issue by nestorjal** [gbif/ipt#1283]
Checking the data  [Data quality requirements](http://www.gbif.org/publishing-data/quality) page  the required fields are: occurrenceID, basisOfRecord, scientificName, eventDate and countryCode. But in the [IPT wiki](https://github.com/gbif/ipt/wiki/occurrenceData#required-dwc-fields) countryCode is missing. 

@kbraak Is this a new update of the required fields?

**Comment by kbraak** [comment]
Thank you for your feedback. 

Please be aware that the [data quality requirements](http://www.gbif.org/publishing-data/quality) are specific to the BID project. In some cases BID may have specific requirements that differ from the [IPT wiki](https://github.com/gbif/ipt/wiki/occurrenceData#required-dwc-fields). Note the reason countryCode was moved from required to recommended is because country borders can change. Instead more emphasis is put on providing location coordinates instead.
