### ISSUE TITLE
IPT uses insecure resources

### ISSUE THREAD

**Issue by timrobertson100** [gbif/ipt#1298]
When running on https users report the IPT will instruct the browser to pull in JS over HTTP in at least one place.  I suspect this may happen if the IPT is sitting behind a proxy which is applying the https.

An example of where users report an issue is on this file:

https://github.com/gbif/ipt/blob/master/src/main/webapp/WEB-INF/pages/manage/eml/geocoverage.ftl#L7

**Comment by MattBlissett** [comment]
I just fixed it, in 595658ceab77886d074d1aa847d69bcd00a389b8

We ought to have an IPT served with HTTPS for testing.

**Comment by kbraak** [comment]
Thanks for raising this issue and for the fix. I applied another fix in https://github.com/gbif/ipt/commit/3289cb2cb7dbb3c9e9f98abad639e3f0a913015a I agree we should have an IPT served with HTTPS for testing. @MattBlissett is this something you can help me set up please?

**Comment by MattBlissett** [comment]
Yes, but I think it would also be a good opportunity to make new servers for the IPT, rather than the collection of spare places we're using at the moment.

That would mean Java 8 (since 7 no longer has public security updates, #1222), and Tomcat 7 (v6 is supported until 31 December 2016).

What's required? Something like
* a development instance, for Jenkins to deploy to every time
* a UAT instance, for deployments of releases for testing
* a prod instance, as ipt.gbif.org is, in test mode so people can fiddle

* completely separately, the instances we have hosting data

**Comment by kbraak** [comment]
Thanks Matt. That sounds good, and thanks for helping setup an IPT on HTTPS for testing. Fortunately this led us to discover the real reason why the map wasn't loading on the Geographic Coverage page: issue https://github.com/gbif/ipt/issues/1302 I'll continue to do more testing on HTTPS, and open new issues for any future issues encountered.

**Comment by kbraak** [comment]
@MattBlissett thanks for setting up http://iptnew.gbif-dev.org/ so that I could test IPT 2.3.3-SNAPSHOT with HTTPS. 

During my testing, I found two additional issues:
1. https://github.com/gbif/validurl-ws/issues/1
2. https://github.com/gbif/ipt/issues/1307

Ultimately to fix both these issues, the IPT web services (gbrds.gbif.org & gbrdsdev.gbif.org) and tools.gbif.org/ws-validurl would need to be served with HTTPS. 

Fortunately a workaround for issue 1. exists and issue 2. does not affect critical functionality. Therefore IPT 2.3.3 can still be released without fixing these issues.

**Comment by kbraak** [comment]
A reminder to also check 

- [ ] call to validurl-ws (gbif/validurl-ws#1) on registration.ftl: `http://tools.gbif.org/ws-validurl/?url=${baseURL}/&callback=?`
- [ ] call to dwca-validator on overview.ftl: `http://tools.gbif.org/dwca-validator/?archiveUrl=${baseURL}/archive.do?r=${resource.shortname}`
