### ISSUE TITLE
A registered resource is shown as no Not registered in the Home Table (IPT 2.3.3)

### ISSUE THREAD

**Issue by cosmicgarden** [gbif/ipt#1319]
I cloned and installed the version 2.3.3 (git clone from master, and after that checkout tag 2.3.3). In this version, some resources are shown as no registered in the Home table, column Organisation, despite already have been registered, whit a link to the dataset in GBIF.

For example, in the SiB Colombia's IPT, the resource http://ipt.biodiversidad.co/sib/resource?r=cnidaria in the table is shown as No registered. 

![image](https://cloud.githubusercontent.com/assets/4042071/22978920/8be92fa4-f362-11e6-92fd-d274e4a7a660.png)

But, this resource has been registered, as is possible confirm in GBIF
![image](https://cloud.githubusercontent.com/assets/4042071/22979077/18f15354-f363-11e6-98f5-7b287ca51c26.png)
http://www.gbif.org/dataset/de10d7a1-a4f7-4aa8-aa1d-72364cecc263

I downloaded the datadir to compare as the resource is shown in the IPT version 2.3.2 and IPT version 2.3.3. In the Home table for the 2.3.2, the organization is shown, but in the 2.3.3, the text "No registered" is shown.

In 2.3.2
![image](https://cloud.githubusercontent.com/assets/4042071/22982226/7fbe1578-f36c-11e6-9594-872496d216d9.png)
In 2.3.3
![image](https://cloud.githubusercontent.com/assets/4042071/22982399/0b516978-f36d-11e6-90cf-9a916da6b784.png)

Looking in the code, in pages/macros/resourcesTable.ftl, a validation of the state  of the resource is made
![image](https://cloud.githubusercontent.com/assets/4042071/22980315/0a5c1960-f367-11e6-8cba-f0dba9ede30d.png)

In the resource's xml, the state is REGISTERED
![image](https://cloud.githubusercontent.com/assets/4042071/22981258/f6bff11c-f369-11e6-9e2b-14428d67dbf0.png)

I think, that the problem is the way the resources are reconstructed, in \ipt\src\main\java\org\gbif\ipt\action\portal\HomeAction.java
![image](https://cloud.githubusercontent.com/assets/4042071/22981563/ba8c4faa-f36a-11e6-96ff-ff04d52a685e.png)
The reconstruction is made using the version published, for the mentioned  case versionHistory has a status PUBLIC
![image](https://cloud.githubusercontent.com/assets/4042071/22981644/f6e104f0-f36a-11e6-9902-17840786a60d.png)

**Comment by kbraak** [comment]
Thanks for reporting this issue and your thorough efforts to debug the issue. 

You are right. This problem was introduced as a result of fixing issue https://github.com/gbif/ipt/issues/1213 in 2.3.3, which ensures the homepage shows the last published version of public resources. If the public resource was registered but never republished, the homepage doesn't reflect that it has been registered - a bug. 

As a workaround, you could republish the affected resources. If that's not an option for some reason, you could manually set the [VersionHistory.publicationStatus](https://github.com/gbif/ipt/blob/master/src/main/java/org/gbif/ipt/model/VersionHistory.java#L128)=REGISTERED inside the resource.xml file of the affected resources. Of course this change would have to be done to the lastest VersionHistory to work. Note, however, that manual updates aren't recommended and a backup of the IPT data directory should always be done before attempting manual updates. 

Lastly, please beware that a snapshot version built from master should never be installed in production. If it's possible, I would recommend upgrading to v2.3.3 using a backup of your v2.3.2 IPT data directory. Note that as a consequence, users will lose any changes made while using the snapshot version. At least this will guarantee that no dangerous inconsistencies were introduced while using the snapshot version though.
