### ISSUE TITLE
Failed to update DOI

### ISSUE THREAD

**Issue by nestorjal** [gbif/ipt#1323]
IPT version: 2.3.3-r01

When trying to publish a new version of a [dataset](http://ipt.biodiversidad.co/sib/resource?r=bios_microorg_seaflower_2016) the following message appears:

![captura](https://cloud.githubusercontent.com/assets/7916426/23266112/c70ae7c8-f9b4-11e6-8fb2-6c7c5474e085.PNG)
```

Publication log:
An error of type DOI was encountered during publishing: Failed to update doi:10.15472/xcpipy metadata: HTTP 500:
Restored version #2.0 of resource bios_microorg_seaflower_2016 after publishing failure 3:58:38 PM

```
I've already checked both data and metadata for inconsistencies but they are fine. 

Any advice?

**Comment by kbraak** [comment]
Thanks Nestor, 

As per [DataCite's API documentation](https://mds.datacite.org/static/apidoc) when encountering a 500 server internal error, you should "try later and if problem persists please contact us". Can you please try again and report back if it works this time?

Otherwise, I'd recommend turning on debugging mode in your IPT settings and looking for more detailed information in your IPT logs. 

By the way, it says your IPT is based on version _"2.3.3-r01"_ but the officially released version is _"2.3.3-rdb4ab13"_. I should raise again the warning in https://github.com/gbif/ipt/issues/1319#issuecomment-280310595 regarding using non-officially released versions in production. 

If you are just customizing the style there is no problem of course. Here is one problem with the re-styling that I noticed by the way:

![screen shot 2017-02-24 at 14 49 49](https://cloud.githubusercontent.com/assets/5981100/23306058/d4a6df70-faa1-11e6-9ae2-583d9796d1df.png)

**Comment by nestorjal** [comment]
Thanks Kyle, today finally the publication was successful. I'll check the issues with the re-styling.

**Comment by kbraak** [comment]
Wonderful, glad to hear that. Thanks for this feedback.
I will close this issue then.
