### ISSUE TITLE
Description paragraph formatting not preserved on GBIF.org after Registry update 

### ISSUE THREAD

**Issue by kbraak** [gbif/ipt#1332]
This issue only occurs when the Admin/GBIF Registration update is run, which updates both the IPT registration and all dataset registrations to ensure their endpoint URLs are correct. 

The consequence of this issue is that datasets whose description is broken into multiple paragraphs will no longer be properly formatted on GBIf.org 

Publishers can fix the issue by republishing the affected dataset.

The [code](https://github.com/gbif/ipt/blob/master/src/main/java/org/gbif/ipt/service/registry/impl/RegistryManagerImpl.java#L130) that populates the request's description parameter can be fixed by wrapping each paragraph inside `<p></p>` instead of separating them with `\n`, which is no longer supported by GBIF for showing paragraphs. 

Note this issue relates to https://github.com/gbif/registry/issues/7

**Comment by mike-podolskiy90** [comment]
Closing this

**Comment by MattBlissett** [comment]
I can reproduce this:

- Create a dataset description with multiple paragraphs (i.e. multiple <para> in the EML)
- Publish
- Should look OK in the GBIF registry
- Administration, GBIF registration options, Update Registration
  - This sends a dataset update to every published dataset, including the description -- but the description here does not support true paragraphs, only line breaks and HTML <p> hacks
- The GBIF registry is updated, and a new crawl would normally be triggered, but the EML is not modified.

But I've fixed it with a change in the registry (as linked above), to ignore updates to the description when the Update Registration button is used.  It is also clearer to publishers if all or none of a dataset's metadata is updated, rather than a few bits being updated first, then the rest relying on a successful EML crawl.
