### ISSUE TITLE
'This resource has not been registered with GBIF' - still in GBIF registration while resource should be registered

### ISSUE THREAD

**Issue by datameister-NL** [gbif/ipt#1352]
Hello,

I am testing our IPT at ipt.ndff.nl but still got 'This resource has not been registered with GBIF' when reviewing metadata of a dataset in private mode. When publishing the metadata to the public, the dataset won't be visible to anyone without rights at our IPT.

What is going on?

**Comment by kbraak** [comment]
I'm afraid I don't understand your problem @datameister-NL - can you please describe it in greater detail? 

I'm sure it would help to review [this section](https://github.com/gbif/ipt/wiki/IPT2ManualNotes.wiki#visibility) of the IPT user manual that explains the different resource states/visibilities. When moving a resource between IPTs, or republishing a resource that has previously been registered with GBIF, it is important to do a so-called resource migration, in order to preserve the GBIF registration and avoid minting yet another GBIF DOI and GBIF key for the same resource. More information about how to do a migration can be found in [this section](https://github.com/gbif/ipt/wiki/IPT2ManualNotes.wiki#migrate-a-resource) of the IPT user manual. 

Lastly, please be aware that a new [IPT demo video](https://www.youtube.com/watch?v=eDH9IoTrMVE) has been released, which demonstrates how to move a private resource to public, in case this helps.

**Comment by kbraak** [comment]
@datameister-NL I noticed that a dataset from your IPT has been successfully registered with GBIF on 2017-09-04 https://ipt.ndff.nl/resource?r=100_000_telmee Therefore I assume this issue has been resolved. Otherwise, please feel free to open a new issue - thanks.
