### ISSUE TITLE
Fix Apache Struts Jakarta - critical remote code execution (CVE-2017-9805)

### ISSUE THREAD

**Issue by bart-v** [gbif/ipt#1359]
https://lgtm.com/blog/apache_struts_CVE-2017-9805_announcement

Security researchers at lgtm.com have discovered a critical remote code execution vulnerability in Apache Struts — a popular open-source framework for developing web applications in the Java programming language. All versions of Struts since 2008 are affected; all web applications using the framework’s popular REST plugin are vulnerable. Shortly after the patched versions of Struts were released on 5 September, multiple working exploits were observed on various internet sites. Users are strongly advised to upgrade their Apache Struts components as a matter of urgency. This vulnerability has been addressed in Struts versions 2.3.34 and 2.5.13.

IPT 2.3.4 has Struts version 2.3.32

**Comment by kbraak** [comment]
Thank you @bart-v

The IPT doesn't use the Struts REST plugin and therefore isn't affected by this particular RCE vulnerability. After careful review, I can also confirm that the version of Struts the IPT uses (2.3.32) is still secure meaning none of the vulnerabilities fixed in Struts versions 2.3.33 or 2.3.34 affect the IPT.
