### ISSUE TITLE
documentation - IP whitelist for IPT installation?

### ISSUE THREAD

**Issue by pdelong42** [gbif/ipt#1410]
I'm at the stage in my installation process where I want to register my IPT with GBIF (/admin/registration.do).  It's prompted me for the Base URL, which I've given it.

However, I wasn't counting on this needing to be public-facing - I was hoping it would only reach out to gbif.org, and not need to be able to take incoming connections from gbif.org.  Therefore I didn't make it publicly-accessible.

So as I'd expect, this step does not succeed: it hangs indefinitely, though it never does time-out (so technically, it hasn't failed).

My question is this: is there an IP or range of IPs for gbif.org that I can whitelist in our ACLs?  I'd rather not open this up to the entire world, for security reasons.  I wasn't able to find anything about it in the docs, but nor did I read the manual cover-to-cover.

Incidentally, I haven't been prompted to choose a license yet.  And I'm assuming this won't be an option until the IPT is successfully registered and we start publishing resources.  Would I also be correct in assuming that applying a license is an operation that a manager with registration rights can do?

Apologies if this is covered in the docs, but I was unable to find a direct reference to it.

**Comment by MattBlissett** [comment]
Hi,

Most users have a public IPT, so this question doesn't come up very often.

The servers are all in `130.225.43.0/24` (a range only for use by GBIF), but staff computers, wifi, VPN and so on are in other ranges which I don't control. (However all in a Danish academic allocation, `130.225.0.0/15`). Please be aware of this if data managers need to ask for assistance from the GBIF helpdesk.

For the outgoing requests the IPT makes, see https://github.com/gbif/ipt/wiki/FAQ.wiki#7-what-outgoing-connections-does-the-ipt-make

Incoming requests will be from servers on the GBIF network, to the endpoints the IPT sends to GBIF when a dataset is published and registered. These endpoints are checked about once per week for any updates.

The license is per-dataset, so that's under the control of the data manager.

**Comment by pdelong42** [comment]
Thanks!  We added 130.225.43.0/24 to the necessary whitelists, and I was able to proceed to the next step.

**Comment by abubelinha** [comment]
@MattBlissett I understand the FAQ link [Installation. 7](https://github.com/gbif/ipt/wiki/FAQ.wiki#7-what-outgoing-connections-does-the-ipt-make) covers both outgoing **and incoming** connections, right? 
If so I suggest to change its title (or adding a different FAQ entry for incoming connections).

Thanks
@abubelinha
