### ISSUE TITLE
CSS issue in Safari

### ISSUE THREAD

**Issue by MattBlissett** [gbif/ipt#1421]
<img width="1361" alt="screen shot 2018-10-01 at 3 51 27 pm" src="https://user-images.githubusercontent.com/583320/46403466-da3b9500-c702-11e8-98d4-d46915869cce.png">

Only a problem in Safari. "I cannot scroll between the different interfaces e.g. Home, Manage Resources etc., because the sentence “Hosted resources available through this IPT” is blocking it."

Could @thomasstjerne or @MortenHofft take a look? The URL is https://cloud.gbif.org/bid.

**Comment by MortenHofft** [comment]
I'm unable to reproduce in my version of Safari. @thomasstjerne ?

**Comment by ManonGros** [comment]
I don't know if it is related but I also have a similar problem when I look at a resource (with safari), if I try the French version.
![screen shot 2018-10-03 at 14 59 02](https://user-images.githubusercontent.com/7677271/46411839-0ebc4a80-c71d-11e8-81df-98d31f3d6f46.png)

**Comment by MortenHofft** [comment]
Turns out it is the same in all browsers if you are logged in and see it in french. Thanks @ManonGros  It is simply the length of the french welcome message that forces the object down. The CSS is made to jump to a new 'line' if the text is moving into the branding header. 

The best fix i can come up with is to let it block the `BID integrated publishing toolkit` text. The design hasn't really been made to be translatable.

**Comment by MortenHofft** [comment]
@MattBlissett I've done the style changes in a separate branch https://github.com/gbif/ipt/tree/mgh-style-change as I haven't run the IPT locally. I cannot imagine it having any crazy side effects. It is simply a changing the position of the login area to be absolute instead of floating.
