### ISSUE TITLE
Spanish translation confusing

### ISSUE THREAD

**Issue by ManonGros** [gbif/ipt#1426]
I think the Spanish translation makes it difficult to understand the difference between "Admin" and "resource manager". Both are translated as "Administrator" (see screenshot below).
Could we find a better translation?
![screen shot 2018-10-29 at 10 51 55](https://user-images.githubusercontent.com/7677271/47642581-50e47a80-db69-11e8-9f29-1da6424181d0.png)

**Comment by timrobertson100** [comment]
Thank you @ManonGros 

Lines 139 and 140 on https://github.com/gbif/ipt/blob/master/src/main/resources/ApplicationResources_es.properties#L139

Can a Spanish speaker please use crowdin and change this (don't commit on the file or it makes a mess)

**Comment by MattBlissett** [comment]
I think the Spanish manual on the wiki would also need updating.

https://github.com/gbif/ipt/wiki/IPT2ManualNotes_ES.wiki

**Comment by MattBlissett** [comment]
In English, the three terms are

* Manager without registration right
* Manager with registration right
* Administrator

Macros suggests:

* Editor con derechos de registro
* Editor sin derechos de registro
* Administrador 

Does that seem reasonable?

**Comment by ManonGros** [comment]
It seems good to me!

**Comment by leobuitrago** [comment]
According to the roles, I suggests:

- Publicador con derechos de registro
- Publicador sin derechos de registro
- Administrador

**Comment by MattBlissett** [comment]
Thanks @leobuitrago. I had a look at the translations, and there are several places where "Manager" or "Administrator" are used. A real Spanish speaker will need to make the changes in CrowdIn, so this hasn't made the 2.4.0 release.

**Comment by MattBlissett** [comment]
@leo-buitrago (or @leobuitrago?), would you sign up in CrowdIn (link above) and make the change to the IPT translation file, and where necessary to the documentation in the wiki? (You have permission on the wiki.)

**Comment by mike-podolskiy90** [comment]
I can update the CrowdIn translations, but we need Spanish speaking volunteers to update the wiki.

**Comment by MattBlissett** [comment]
I've updated in CrowdIn, Marcos has reviewed, and I've tried to update the wiki as best I can: https://github.com/gbif/ipt/wiki/IPT2ManualNotes_ES.wiki

We discussed and chose:
```
Gestor con derechos de registro
Gestor sin derechos de registro
Administrador
```

It will be merged with #1567.

**Comment by MattBlissett** [comment]
Hi @daiesco,

Thanks for you and your team's efforts translating the IPT UI and manual.

I see you've changed the translation of resource manager back to "administrador", which was changed because some users found it confusing.

We had four suggestions:

* Administrador con derechos de registro
* Administrador sin derechos de registro
* Editor con derechos de registro
* Editor sin derechos de registro
* Publicador con derechos de registro
* Publicador sin derechos de registro
* Gestor con derechos de registro
* Gestor sin derechos de registro

If administrador is the best choice, note there are a few more cases of "gestor" in the user manual. It would be easiest to find them with a search: https://crowdin.com/translate/gbif-ipt/all/en-esco?filter=basic&value=3#q=gestor

**Comment by daiesco** [comment]
Hi @MattBlissett!

You are right, I will review this issue in detail to avoid conflicts between Admin and Manager.

**Comment by daiesco** [comment]
@MattBlissett, all related strings have been upgraded ;-)

English terms:
    Manager without registration right
    Manager with registration right
    Administrator

Spanish terms:
    Editor con derechos de registro
    Editor sin derechos de registro
    Administrador

**Comment by MattBlissett** [comment]
Thanks, and I see the UI translation is 100% done, excellent.

I've updated the deployment on https://ipt.gbif-uat.org/ and it looks fine.
