### ISSUE TITLE
How to cite, the year doesn't get  updated

### ISSUE THREAD

**Issue by camiplata** [gbif/ipt#1446]
The year of the  'How to cite' metadata section doesn't get  updated at the IPT after publishing.

We (@SIB-Colombia) detected this issue in the following resource: [https://doi.org/10.15472/icidip](https://doi.org/10.15472/icidip)

See 'How to cite' at  IPT:

![image](https://user-images.githubusercontent.com/5700527/55912672-ce94c380-5ba8-11e9-9933-f53d7f93bd3b.png)

See 'How to cite' at GBIF

![image](https://user-images.githubusercontent.com/5700527/55912838-d94f5880-5ba8-11e9-8623-5b6937752405.png)

**Comment by MattBlissett** [comment]
The citation is regenerated when the resource is published, but the year is set to the year the resource was first published.

https://github.com/gbif/ipt/blob/f6dec1f48465a95d4427f41f50f6b58b7ed2c6a5/src/main/java/org/gbif/ipt/model/Resource.java#L1060-L1066

It's been that way since auto-generating citations was implemented, but that doesn't seem right. I'll change it to the current year.
