### ISSUE TITLE
Advice on publishing a plant usages dataset

### ISSUE THREAD

**Issue by rukayaj** [gbif/ipt#1485]
Hi folks, I have a dataset of plant usages (mostly medicinal + food) which I want to publish to GBIF. I think it's probably most appropriate as a checklist?

There are multiple usages per plant, and each usage is associated with a particular geographical location and with particular vernacular names. I was thinking if I publish a checklist with one row per usage I would have duplicate scientific names BUT I would be able to: 

- use the taxonid with the speciesdistribution extension http://rs.gbif.org/extension/gbif/1.0/distribution.xml in order to tie specific plant usages to places, and 
- use the taxonid with the vernacularnames extension http://rs.gbif.org/extension/gbif/1.0/vernacularname.xml to tie specific plant usages to common names.

If there's a better way to go please let me know. I guess an alternative would be to collapse the data and publish a normal non duplicate checklist, losing the common name <-> usage and place <-> usage relationships, but that's not great.

Edit: I would use the MeasurementOrFact extension to publish plant usages as facts.

**Comment by abubelinha** [comment]
I am also very interested in this issue.

In my opinion, sometimes the information about vernacular names and plant usages looks more like [occurrence data](https://github.com/gbif/ipt/wiki/occurrenceData).
But for some reason, the IPT allows only [checklist data](https://github.com/gbif/ipt/wiki/checklistData)sets to be extended with the [vernacular names extension](http://rs.gbif.org/extension/gbif/1.0/vernacularname.xml).
 
A practical example: an herbarium collection of labeled plant specimens, which are already published to gbif as an occurrence dataset. For now, only some core-occurrence concepts have been mapped, like institutionCode, collectionCode, basisOfRecord, catalogNumber, recordedBy, ScientificName, and several location related concepts.

But what if in the specimen labels there are also vernacular names and plant usages which we want to be published to gbif?
Let's say, one specimen collected in a certain country, contains 3 labels informing about the different vernacular names and popular usages of the species, in 3 different places around the location where the specimen was collected.
And the same for other specimens of the herbarium, collected in different places around the world.

As we cannot apply the vernacular names extension to the occurrence data, we have to cope with producing a checklist. But doing so, how can we link the vernacular names information to the original herbarium specimens where it comes from?
Looks like the only way is using the dcterms:source field, but I don't think that will permit people to navigate between the vernacular name and the herbarium specimens, when they are browsing either the occurrence or checklist datasets, Am I wrong? 

Another problem I found is mapping the medicinal/food plant usages:
I don't see an appropiated field to store this information, either in core definitions ([checklist](http://rs.gbif.org/core/dwc_taxon_2015-04-24.xml) / [occurrence](http://rs.gbif.org/core/dwc_occurrence.xml)) or extensions (vernacular names). @rukayaj mentions the [species distribution](http://rs.gbif.org/extension/gbif/1.0/distribution.xml) extension for that purpose, but I don't see any appropiated field there either.
Perhaps the [measurements or facts](http://rs.gbif.org/extension/dwc/measurements_or_facts.xml) extension? This can be applied to both occurrence and checklist data, but I am not sure if it is appropiate for this purpose.

Finally, I am a bit lost about how to link the extension to the checklist core. as @rukayaj says the checklist would have duplicated names, but I don't see why should that happen.
Isn't the taxonid supposed to act as a 1:N key which should avoid that problem, so it is used to link each taxon name with its corresponding vernacular names, once both text files are merged into the darwincore file?

Please somebody at gbif could enlight us on this? It would be great having a sample file to download and use as a model to follow.

Thanks a lot

**Comment by rukayaj** [comment]
@abubelinha I ended up using a checklist core with duplicate scientific names as I described, so that each use (stored in measurement or facts) is related to one record, e.g.: 

https://www.gbif.org/species/164940157/verbatim
https://www.gbif.org/species/164940159/verbatim

This means that a specific plant use can be linked to a specific location and a specific vernacularName, which is important in this dataset (e.g. to know that in this part of Norway this plant was used for veterinary purposes and it was called X, whereas in this part of Sweden it was used as animal food and it was called Y). 

Anyway even though I have published the dataset I will leave this issue open as I'm still interested in feedback from GBIF, and the case you describe where you want to link occurrence data with vernacular names seems relevant.

**Comment by abubelinha** [comment]
OK, I see now why you suggested to use the species distribution extension.

But the way you constructed [your checklist](https://www.gbif.org/dataset/e1fd4493-a11a-438d-a27f-ca3ca5152f6b) core data looks a bit odd to me, in the sense that you are **not** using a single record for each taxon name. You are generating many different taxonIDs for the same taxon (for example, _Achillea millefolium_ has near 25 different taxonids, as I see in the taxon.txt of your DwC zip file). 

Of course you get your data published and the info is available. But it is not easy to browse: you can **not** click on a taxon and see all different vernacular names and usages associated to that species in the different locations and dates.

I would like to have some gbif feedback here (perhaps @mdoering or @timrobertson100 ?), but in my opinion this approach goes against the idea of how a taxon checklist should be constructed.  
Or at least from this image in  https://github.com/gbif/ipt/wiki/BestPracticesChecklists#checklist-data , I get the idea that a taxonID should be like a primary key (only one taxonID for each species present in the core _A_ file),

![image](https://user-images.githubusercontent.com/698946/87245795-b1544200-c448-11ea-9033-18423db3d7c3.png)

The point is: Should I follow your example when I publish our similarly structured data?

In our case: many plant **specimen samples** collected at schools; associated to each one there will be a taxonomic identification (so, for now, this is just an occurrence dataset). 
But there will also be specimen-attached **enquiries** made to neighbours asking them for information about **vernacular names** and human **usages** of that plant in a particular **location** and **date**. Also, an enquiry could have **associated media** (images and sound or video recordings, mostly stored at youtube/google drive).

What way should I publish it, so all that info -names and plant usages from every location- is alltogether visible in the taxon page?

**Comment by mdoering** [comment]
It seems the DwC scheme does not fit perfectly here. Checklists with a taxon core feel mostly right, but the core taxon record ideally should indeed be unique and not duplicated if you know these are the same taxa. There is no location or time information in the taxon core, it is purely the taxon concept. Both the distribution and vernacular names extension allow to assert a geographical context, but they do not allow to cross reference each other. But you can say that this particular vernacular names is used in this location of sweden. 

As for human use of a taxon I am not aware of such an extension. But if you/we would craft one I assume it would also have a geographical context. I have not seen you examples, but how would you use the distribution in that case? Where would you put the kind of use/usage?

**Comment by abubelinha** [comment]
Thanks @mdoering 
The example is not mine but from @rukayaj (who opened this issue, although their nice [dataset of nordic plant uses](https://www.gbif.org/dataset/e1fd4493-a11a-438d-a27f-ca3ca5152f6b) is already published).
I am interested in the issue because I want to publish similar data from another country (but based in oral enquiries rather than in published references).

I understand they used the [distribution extension](http://rs.gbif.org/extension/gbif/1.0/distribution.xml) as a mean of locating each plant usage in Norway. 
But, as distribution extension is supposed to be referred to a taxon, I guess that was the reason they decided to repeat taxons so many times (with different taxonids): that way they could refer different locations and usages of the "same" taxon.

As for the human usages of species, they used the [Measurement or Facts extension](http://rs.gbif.org/extension/dwc/measurements_or_facts.xml): in "measurementType" column they put "usage" for all rows, and in "measurementValue" column they described things like "animal food", "veterinary", "medicine" and so on. This extension does not provide geographical context, but as they are linking to different taxonids each time, the aforementioned distribution extension solved the problem.

A couple of their examples:
https://www.gbif.org/species/164940120/verbatim
https://www.gbif.org/species/164940135/verbatim

As you can see, both are referred to the same species (_Achillea millefolium_). 
They created different "taxon instances" (taxonIDs), so each one could be linked to a bunch of usages ([measurements or facts](http://rs.gbif.org/extension/dwc/measurements_or_facts.xml) + their [distributions](http://rs.gbif.org/extension/gbif/1.0/distribution.xml)), [vernacular names](http://rs.gbif.org/extension/gbif/1.0/vernacularname.xml), and also literature [references](http://rs.gbif.org/extension/gbif/1.0/references.xml).

So, that is not a "taxon checklist" anymore. It is more like a repetition of taxons, so to me it makes more sense to **(1) publish it as occurrence data** as far as it can be somehow extended with plant usages and vernacular names as well (vernacularName is an available term in the occurrence data, but for plant usages I would need something else).

If we still prefer to **(2) produce a real taxon checklist**, one possibility which comes to my mind is extending that [checklist data](http://rs.gbif.org/core/dwc_taxon_2015-04-24.xml) with [occurrence data.](http://rs.gbif.org/core/dwc_occurrence_2020-04-15.xml)
This sounds odd since both of them are normally used for publishing the core of a dataset (either species or ocurrences).
But when playing with our IPT, I noticed that after selecting "taxon checklist" as the core dataset, then "occurrence" becomes also available as an extension for that dataset. 

Can you tell me what is the expected use case for that combination?
Again an example dataset would be great: I can't predict how that would look like in gbif portal (and I don't think it is OK to publish a dataset just for testing purposes, and deleting it later on).

I don't think **(3) an event dataset** would be appropiate. In the sense that enquiries about vernacular names or plant usages could be considered a kind of "event". That would be a "human sampling event" rather than a "biological sampling event", so I don't think this is one of the intended purposes of event datasets.

**Comment by rukayaj** [comment]
Yes that's right, I have duplicated taxa because I wanted essentially to publish a checklist of plant uses, rather than a checklist of plant names. Rather than showing "_this particular vernacular name is used in this location of sweden_", I wanted to show that this particular **plant usage** (which I have published as a MeasurementOrFact) is tied to this vernacularName and this location. I could have included locality data in the VernacularName extension as well as (or instead of) the Distribution extension. 

I'm not sure that I've done the optimal thing here, as you say it's not all that easy to browse but on the other hand at least it is possible to reconstruct the original data without losing valuable information. 

As it's possible for taxon X to appear in several checklists, I feel like perhaps it's not a big deal to have a single checklist with a taxon multiple times?  I am not really sure though, it feels like there isn't a very good fit with any of the different datatype options as they are. 

If I had used the one core to many extensions model (the one in the diagram you posted), how would I have linked particular VernacularNames to particular MeasurementOrFacts? I don't think it's possible. Publishing it as occurrence data as you suggest is a more sensible option. But on the other hand, this is not really a list of occurrence data.

I have never heard of a checklist dataset which has an 'occurrence' extension. You could always try publishing it on gbif-uat and a test IPT and seeing what happens? If you have a one to one relationship between them (i.e. each taxon record has only one occurrence record) that might work? But as I say, I feel like these datasets aren't really occurrence data.

**Comment by abubelinha** [comment]
Thanks for your advice @rukayaj 
I never tried that gbif-uat testing thing. How does that work?
A test IPT needs to have a public IP or could it run in localhost for that testing purposes?

**Comment by rukayaj** [comment]
GBIF has a testing environment https://www.gbif-uat.org/, your test IPT (which must have a public IP address) will publish to there. I think it does need to be publicly accessible, as far as i'm aware it's an exact mirror of production. So everything should work exactly the same. If you want you can use Norway's test IPT, just send me an email to rukayasj@uio.no.

**Comment by rukayaj** [comment]
Sorry @mdoering I didn't notice your suggestion of a new extension. It could be something like this. 

| id | taxonID                              | vernacularNames (associated with uses and distribution)     | vernacularNamesLanguages | taxonParts                  | usage            | distribution                                        | additional                                                                                               | reference                                                                                                                           |
|----|--------------------------------------|--------------------------------------------|--------------------------|-----------------------------|------------------|-----------------------------------------------------|----------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------|
| 1  | 86da7f38-2fcb-4719-8433-c77b9744323c | tilg\|molfoor-tilg\|talg\|tælg\|tælgblom   | NO\|NO\|NO\|SV\|SV       | seedlings, germinated seeds | alcoholic drinks | Tromsø, Norway\|Helgeland, Norway\|Beitstad, Norway | {"treats": ["gout", "joint pain"], "application": "oral ingestion", "preparation": "boiled"}             | Høeg OA. (1974). Planter og tradisjon: floraen i levende tale og tradisjon i Norge 1925-1973. ISBN 8200089304.                      |
| 2  | 86da7f38-2fcb-4719-8433-c77b9744323c | orme-blom\|ormeblom-ving\|største ormeblom | NO\|NO\|SV               | leaves                      | poultice         | Siberia                                             | {"treats": ["wounds"], "application": "placed on wound for 5 days", "preparation"" "pounded and mashed"} | Jørgensen PM, Weidemann E, Fremstad E. (2016). Flora Norvegica av JE Gunnerus. På norsk og med kommentarer. ISBN 978-82-8322-077-3. |
| 3  | 86da7f38-2fcb-4719-8433-c77b9744323c | cheek                                      | FI                       | fruits                      | food             | Finland                                             |                                                                                                          | Jørgensen PM, Weidemann E, Fremstad E. (2016). Flora Norvegica av JE Gunnerus. På norsk og med kommentarer. ISBN 978-82-8322-077-3. |

That should also give you an idea of what the data might look like. Feels a bit weird to be adding that when we already have an extension for vernacular names though. I'm also not sure how to treat all the additional information my dataset has, so I stuck it in as json.

**Comment by ahahn-gbif** [comment]
Thanks, @rukayaj, @abubelinha,
this is an interesting discussion. It indeed seems that no constellation fits perfectly, and it will also depend on whether you are mostly valuing your own, local resource describing the contents of your data as completely as possible, or more focusing on the integration with other datasets.

If the information is taxon-focussed (and now echoing @mdoering), then starting from a taxon core does sound right, though indeed ideally each taxon should only appear in the taxon core once in that case. What you are trying to model, though, is a matrix where each taxon has x vernacular names and y uses, and where a specific use is tied to a (or several) specific vernacular name(s), and vice versa. The vernacular name extension (https://tools.gbif.org/dwca-validator/extension.do?id=gbif:VernacularName) does allow to specify a locality, so depending on your goal, you may not need the distribution extension. The use (via Extended Measurements Or Facts), though, would still not be cross-referenced to the vernacular names; as you say, this would not be possible - it is one of the limitations of the "star schema", as in the sketch above. As a result, the information is available in the verbatim data, but appears a bit more confusing at the higher level of a search result (https://www.gbif.org/species/search?q=Achillea%20millefolium&dataset_key=e1fd4493-a11a-438d-a27f-ca3ca5152f6b&origin=SOURCE&advanced=1). This is a trade-off - the 1:1 mapping allows to document that relationship for users of the source file and the verbatim data, but makes it more obscure on the integrated view.

Concerning extending checklist data with occurrence data: that model is by no means uncommon. It is basically a shift of the view, from a more object-focussed (occurrence core, names already included: identified specimens from collections, or species spotted in the wild at a certain time and place), to a taxon oriented one. that could be a floristic dataset, with records of concrete occurrences attached as evidence; a checklist of newly described taxa, referencing the specimens examined or deposited; or a [taxonomically focused catalog ](https://www.gbif.org/dataset/da38f103-4410-43d1-b716-ea6b1b92bbac) capturing distribution information and evidence of occurrences.

**Comment by abubelinha** [comment]
> GBIF has a testing environment https://www.gbif-uat.org/, your test IPT will publish to there. I think it does need to be publicly accessible, as far as i'm aware it's an exact mirror of production. So everything should work exactly the same. If you want you can use Norway's test IPT, just send me an email to [rukayasj@uio.no](mailto:rukayasj@uio.no).

Thanks a lot for your offer @rukayaj 
I preferred to set up a test IPT server, since I need to map against a mysql which is not accesible to external machines.

But I am having troubles to get a simple test published. @ahahn-gbif : how long does it take a 100 records checklist to get visible in gbif-uat when [registry health is reported as "Operational"](https://www.gbif-uat.org/health)?

**Comment by rukayaj** [comment]
Thanks for your feedback @ahahn-gbif. 

Another option I thought of is to publish a version of the data on GBIF which doesn't include the data linkages, but to dump the original spreadsheet on a data archival system like Zenodo. One could then note in the metadata that some of the information has been lost through the limitations of the star schema, but that the full dataset is available for download separately on Zenodo, and provide the link. As you say though, it's a trade off so I suppose each data publisher will just decide for themselves how best to do it. Looking forward to seeing your dataset @abubelinha :)

**Comment by ahahn-gbif** [comment]
@abubelinha, it should not take that long; the first step would be for it to turn up in the uat registry though; after that, indexing can pick it up. At the moment, the last dataset registration there shows to be from July 13th, but that is an internal one. 
Could you give us a few more details? Which organization did you register the dataset against in the IPT, or do you still need the token for one of the test organizations to do so? What dataset title and organization should we look out for? Please feel free to write to helpdesk@gbif.org if any of the information you plan to send is security-relevant.

**Comment by abubelinha** [comment]
Sorry @ahahn-gbif , my fault. 
Some ipt configuration steps are still missing: I forgot about organization token/password (thought it was not needed for test installations).

**Comment by abubelinha** [comment]
@ahahn-gbif one question about this warning when you click the "Register" resource button:

![image](https://user-images.githubusercontent.com/698946/87810297-0d5e0280-c85d-11ea-8099-373576399756.png)

I do not understand why it says  "_**deletion** from the GBIF Index is automatic, but cannot be undone_".

Isn't that a mistake?
We are not **_deleting_** anything when we register a new resource. We are doing the opposit thing. Am I wrong?

**Comment by ahahn-gbif** [comment]
Hi @abubelinha, I agree the phrasing is a bit confusing in the context. 

The intention is to avoid a situation where a resource is registered somewhat prematurely, maybe just to get a first impression of what the public version would look like, but then deleted again to withdraw the now public version, in order to make some more changes before attempting to register it again for good. And that is not possible through the IPT - a dataset can be registered, and it can be deleted again if need be, but that deletion is then irreversible, at least from within the IPT.

**Comment by abubelinha** [comment]
> The intention is to avoid a situation where a resource is registered somewhat prematurely - a dataset can be registered, and it can be deleted again if need be, but that deletion is then irreversible, at least from within the IPT.

Thanks @ahahn-gbif 
So the warning is mostly for not loosing the url of the resource.

But if you don't mind changing that url, you can always publish a resource, delete it (if there is a problem), and republish it later again as a new resource (with a different url). Correct?

**Comment by ahahn-gbif** [comment]
Technically correct, @abubelinha. This would mean starting the configuration over on the IPT, though - it will not allow you to register the same setup a second time. If it becomes necessary, the earlier registration can be manually 'resurrected', but that requires helpdesk intervention.

We would generally recommend to keep dataset IDs as stable as possible, not least because external data (usage reports, data citations) will likely be referencing them. That may not be so much of an issue early on, of course.

**Comment by timrobertson100** [comment]
@ahahn-gbif, can you please summarise any changes are needed or should be considered in the IPT in light of this discussion?

Or can this be closed please?
