### ISSUE TITLE
401 error when trying to publish using IPT in test mode

### ISSUE THREAD

**Issue by matdillen** [gbif/ipt#1512]
I tried to publish a new version of a dataset on our IPT in test mode, to test the new Agents Attribution extension. Publication was successful until the end, when it threw the following error:

`An error of type REGISTRY was encountered during publishing: There was an error in GBIF Registry update – Update resource registration failed [shortname=meiseherbarium, key=[a guid]]: HTTP/1.1 401 Unauthorized. 12:31:13 PM`

(I redacted the guid in case it's not supposed to be shared.)

**Comment by ahahn-gbif** [comment]
Hi @matdillen, we tried to look into this, but have a few questions. We identified the UUID as b6680ce5-48d6-4e96-b95d-d5c0b4ca33cc (there is no security risk with showing that) - could you confirm that this is the right one?

I would also like to confirm whether I understand the situation correctly. Is it correct that you have a dataset configured on a test-IPT; this dataset had previously been registered to https://registry.gbif-uat.org/ and indexed at https://www.gbif-uat.org/; you had now changed your configuration in your IPT and tried to republish the dataset, but received the error message you cited?

gbif-uat is a copy of the production environment, and it is possible that a refresh of that copy caused datasets to disappear that had previously been registered to uat as a test environment. If this is indeed the reason for the error you got, you would need to register the dataset as a new instance, rather than an update to an existing one. It would help us finding out more if you could tell us 
- which publisher and installation the dataset was registered to. Would that be https://www.gbif-uat.org/publisher/a344ee9f-f1b7-4761-be2c-58ee6d741395 and https://www.gbif-uat.org/installation/5580b379-66a7-445d-aab4-63103aaa78dc?
- the address of your test IPT installation. I do find https://registry.gbif-uat.org/installation/5580b379-66a7-445d-aab4-63103aaa78dc in the registry, but it has no registered endpoint or datasets attached. Could you share the address of that IPT installation? If you do not want to leave it here, you could also send an email to helpdesk@gbif.org, but remember that as a registered installation, it would be public anyway

**Comment by matdillen** [comment]
Hi @ahahn-gbif,

That is indeed the correct UUID, publisher and installation. The address of the test mode IPT is http://ipt-dev.br.fgov.be:8080/ipt/

I published a dataset with this test IPT back in April this year and it seems to have disappeared since then. I suppose that's why updating with a new version does not work?

So I have to make a new dataset on our test IPT and publish that? Or is there a workaround? Can I somehow copy the old one, to avoid re-entering all mappings and metadata?

**Comment by ahahn-gbif** [comment]
Hi @matdillen, ideally we would just want to make your dataset unaware that it had already been registered in the past, so that you don´t have to create a new one. 

To do so, find the resource.xml of your dataset in the file system, and
- remove the <key>...</key> part
- change <status>REGISTERED</status> to <status>PUBLIC</status>
and
- remove the GBIF UUID from the additional metadata - identifiers section

Could you let us know how that goes?
Thanks, Andrea

**Comment by matdillen** [comment]
Hi @ahahn-gbif 

We had to modify the xml file and reboot tomcat twice for some reason, but then it worked. The dataset seems to have been successfully ingested now.

thanks!

**Comment by ahahn-gbif** [comment]
Happy to hear, @matdillen, thanks for letting us know! I'll close this issue then.
