### ISSUE TITLE
Accidentally hitting "Publish all resources" button

### ISSUE THREAD

**Issue by cornthwaitem** [gbif/ipt#1554]
We ran into an issue where the "publish all" button got pushed by accident, so all the OBIS Canada datasets started to republish.  I know this button can be really useful in some situations, so I wondered if there could be a safeguard such as a "cancel all" button, or a popup if you push the publish button that says "are you sure?" with the option to say ok or to cancel.

**Comment by mike-podolskiy90** [comment]
Thank you @cornthwaitem 
I think a popup window will help here (like publish or delete buttons).
Functionality will be added to the 2.5.0 release

**Comment by mike-podolskiy90** [comment]
@timrobertson100 @MattBlissett do you have any suggestions for the text of the popup?

**Comment by MattBlissett** [comment]
I think the button should probably be moved, it's not in a great location.  Perhaps put it in its own section, rather than within the "IPT settings" box:

![image](https://user-images.githubusercontent.com/583320/118945293-9d754880-b955-11eb-96ac-17efa83d35b2.png)

I won't redo the screenshot, but text like "Bulk publication" or "Mass publication" would be a better label.

There is very little documentation that would need to be updated.

The text that's in the ⓘ button (admin.home.publishResources.help) at the moment can then be adjusted slightly and shown on a separate page:

----

## Publish all resources

This button will republish *all* resources¹. 

For each resource, it will create a new Darwin Core archive, EML metadata and RTF.  It will notify the GBIF registry of the new publication, and update the IPT's metadata in the registry².

Use this button if:
a) Multiple resources have been updated, and you want to publish a new version for all of them instead of publishing them individually.
b) the Base URL has been changed and you want to update the IPT's registered datasets to reflect the change.

[Publish³ all resources]

¹ Is it all resources, or only resources that are currently published?

² Does it? Or does it update the datasets' metadata (endpoint etc?)

³ "Republish" might be better

----

Clicking the button can then make a popup "Are you sure? Publish / Cancel".

Later, we can also add another button to this page for updating endpoints only, without republication — i.e. for case (b) above, which is probably much more common.

**Comment by mike-podolskiy90** [comment]
![Screenshot 2021-05-21 at 11 08 08](https://user-images.githubusercontent.com/24795387/119113215-29a27100-ba25-11eb-969f-49908aef276a.png)

**Comment by mike-podolskiy90** [comment]
![Screenshot 2021-05-21 at 11 11 28](https://user-images.githubusercontent.com/24795387/119113368-52c30180-ba25-11eb-884c-fb2272a1d901.png)

**Comment by mike-podolskiy90** [comment]
Will be included to the 2.5.0 release. Close this
