### ISSUE TITLE
can't register dataset: IO error occurred while trying to communicate

### ISSUE THREAD

**Issue by PietrH** [gbif/ipt#1577]
When trying to register a public dataset from our IPT, we are running `IPT Version 2.4.0-r6f4f375`

The error from the logs; 
```
ERROR 21-May-2021 16:32:05 [org.gbif.ipt.action.manage.OverviewAction] - An IO error occurred while trying to communicate with the GBIF Registry. [https://gbrds.gbif.org/registry/ipt/resource]
ERROR 21-May-2021 16:32:05 [org.gbif.ipt.action.manage.OverviewAction] - Registration of resource failed!
```

Possibly related:
```
WARN  21-May-2021 16:31:20 [org.gbif.ipt.action.AccountAction] - CSRF login token wrong! A potential malicious attack.
```

I've logged in and out again, and cleared cache. I've also tried removing some unused source files. A colleague was also unable to register the same dataset (from a different machine/account).

**Comment by MattBlissett** [comment]
Hi Pietr,

The CSRF log is a different bug (the reason it's sometimes necessary to try and log in twice), and has already been fixed for the next release.

Is there any additional information in the debug log?  You would need to click "Download the complete log file" to see the non-Warning messages, but they could help show where the problem is.

It could be the publishing organization password is incorrect (though this seems unlikely).  It could be the data sent to the registry is somehow corrupt.  It could also be some sort of network problem sending the request.  Does apm-ipt.br.fgov.be use a proxy server? I don't see any requests from its IP, 193.190.116.21

**Comment by matdillen** [comment]
Hi Matt,

This is what I found in the debug log after login and trying to register the dataset once more.
[debug.log](https://github.com/gbif/ipt/files/6553553/debug.log)

There's some warnings, but nothing that seems informative about the cause of the I/O error.

The following error has been popping up at irregular times, including last night, unrelated to management activity on the IPT. It mentions `IOException: Broken pipe`:

[error.log](https://github.com/gbif/ipt/files/6553619/error.log)

Something else that may be worth mentioning: last month, our IPT instance had to be powered down during server maintenance.  We had trouble connecting to the data directory after relaunching the VM. Initially, the IPT failed to find any datasets, but after some time the problem resolved itself. Maybe the password was corrupted/lost during this process, so it may be reasonable to re-enter it? I don't think I have this password though.

**Comment by MattBlissett** [comment]
I don't see anything in our API logs from 193.190.116.21 / apm-ipt.br.fgov.be, and all IPT API requests so far today have been successful.

Would you check the proxy configuration in the IPT correct, and whether the server can connect to https://gbrds.gbif.org/ ?  e.g. `curl -I https://gbrds.gbif.org/` if it's Linux. (i.e. check if any firewalls are blocking the requests).

**Comment by matdillen** [comment]
Hi Matt,

We did the curl and it succeeded, although it took some time. I don't see anything wrong in the proxy settings (I omitted the analytics key):

```
#IPT configuration, last saved Wed Nov 11 19:21:38 CET 2015
#Wed Nov 11 19:21:38 CET 2015
debug=true
archivalMode=false
location.lat=50.926324
proxy=
#ipt.baseURL=http\://apm-ipt.br.fgov.be\:8080/ipt-2.4.0
ipt.baseURL=http\://apm-ipt.br.fgov.be\:8080/ipt
analytics.gbif=true
location.lon=4.333686
```

Others I can find from the admin panel:

IPT data directory: /data/ipt

IPT log directory: /data/ipt/logs

GBIF Registry URL: https://gbrds.gbif.org

Another thing I can think of that may be relevant: last year we requested some metadata updates to our installation and publisher page on GBIF. Is it possible this may cause error? Although then you should see some requests coming at least from our end...

**Comment by MattBlissett** [comment]
I do see the curl test in our logs, but nothing else:

```
193.190.116.21 915 - [27/May/2021:13:27:47 +0000] "HEAD http://gbrds.gbif.org/ HTTP/1.1" 200 0 '-' 'curl/7.47.0'
193.190.116.21 926 - [27/May/2021:13:53:14 +0000] "HEAD http://gbrds.gbif.org/ HTTP/1.1" 200 0 '-' 'curl/7.47.0'
```

It should be fast though; less than 0.5 seconds (similar to opening the page in a web browser). Is it still slow a second/third/fourth time? Are there many processes running on the server? (Has it been hacked?) 

If there's a problem with the network, it might show up when requesting a larger file (this is on the same server) :
```
time curl -o /dev/null 'https://api.gbif.org/v1/image/lztLgddXfy6sr6zE0y_tf-oufFc=/http://specify-attachments-saiab.saiab.ac.za/originals/851.tif'
```
(Try several times, it takes under 3 seconds from my desktop computer.)

If the "curl" commands aren't working reasonably quickly and reliably, the problem is probably not with the IPT but with either your server, your network, or your network's connection with GBIF's network.

**Comment by nikodm** [comment]
Hi all,

I checked the suggestions made by Matt:

When requesting the larger tif-file, response times were significantly slower during the first requests then they are now.
During the first attempt this could take up to 17 seconds. For all my latest requests I got a response between 1 to 6 seconds. (most of the time it turns around 1 sec)

I also tested from other servers (being in our DMZ or internally) and these give similar response times. 
So DNS could be involved here...

Although the VM doesn't have a lot of memory (4 GB), it's almost not using any cpu at all.

**Comment by matdillen** [comment]
I tried registering the same dataset using our IPT test mode instance, which was successful. I manually added mapping and metadata instead of importing the DWC-A, just in case this had any impact.

Then I tried registering the dataset on our production IPT and there was no error this time. https://www.gbif.org/dataset/9be00561-9236-462f-b536-4a073b4f02f7

The ingestion is still ongoing, but the **issue seems to have resolved itself**. That still leaves the question of what caused it? For a few days at least (and possibly much longer), our IPT failed to successfully register new datasets.

**Comment by MattBlissett** [comment]
> When requesting the larger tif-file, response times were significantly slower during the first requests then they are now.
> During the first attempt this could take up to 17 seconds. For all my latest requests I got a response between 1 to 6 seconds. (most of the time it turns around 1 sec)

The first request will pull the large image into our cache, and subsequent ones should be served from cache.  Trying just now, it takes 11s, 2.7s, 2.6s, 2.8s, 2.5s for me at home.
 
----

I'm pleased it's working now, but without knowing what caused it there won't be anything we can do to fix it, so I will close this issue.  My suspicion is some sort of networking issue on the server.

Let us know if you see the same problem in the future.
