### ISSUE TITLE
Provide a troubleshooting page

### ISSUE THREAD

**Issue by MattBlissett** [gbif/ipt#1580]
It would be helpful to have a "Troubleshooting" page, showing the status of some common causes for failure and hence support requests.

* Network access on HTTP and HTTPS to https://gbrds.gbif.org, http://rs.gbif.org
* Public network access, tested using the service on https://tools.gbif.org
* Data directory: writeable and disk space remaining
* Operating system, Java version (like we have in the HTTP client user agent: `GBIF-IPT/2.4.2-rd9bfb4b (+https://www.gbif.org/ipt) Java/1.8.0_131 (Linux)`).
* Test/Production mode

The first two would be useful on their own, by the relevant administration settings and perhaps during setup.

**Comment by sylmorin-gbif** [comment]
Here is my first version:
![image](https://user-images.githubusercontent.com/56630013/119948617-4ac10f80-bf99-11eb-8783-1d4a4bf8838b.png)

**Comment by sylmorin-gbif** [comment]
I have few questions:

1) Public network access, tested using the service on https://tools.gbif.org
Checking https://gbrds.gbif.org, http://rs.gbif.org should be enough to check public network access?
Or is the specific URL https://tools.gbif.org used in the code, and worth a check? (I can find references but not real calls) 

2) I set a limit to 80% of disk usage, to display it in red. Do you agree?

3) Is this page restricted or public?

4) Should we add a menu entry for this page?
Maybe the gbif.org ![image](https://user-images.githubusercontent.com/56630013/119948842-8cea5100-bf99-11eb-8713-4da68d2ec9aa.png) icon, near the login button?

5) Related to #3, I didn't display the real paths of the file permissions tests (config directory path, etc...), because we usually avoid to display publicly system information (to prevent attacks).

However, I realize that, at startup, we do such tests and display the paths:
![image](https://user-images.githubusercontent.com/56630013/119948963-aab7b600-bf99-11eb-9172-2c56d0cf70bc.png)

What do you think about it?
To be consistent, should we display the paths everywhere, or hide them everywhere?

For ease of use, I would keep displaying them, because I guess all IPT users are not comfortable with checking the logs for such warnings.

And if we want to be really secure, we should also prevent displaying stacktraces in the UI, etc... but it will make the bug reporting more difficult.
 
Cheers,
Sylvain

**Comment by sylmorin-gbif** [comment]
What about this UI instead?
I think the block titles are more readable (highly inspired by gbif.org :) ) but it's a bit less compliant with the IPT stylesheet.

![image](https://user-images.githubusercontent.com/56630013/119951966-cec8c680-bf9c-11eb-8d54-17cf51c38861.png)

**Comment by sylmorin-gbif** [comment]
I also added a JSON output:

![image](https://user-images.githubusercontent.com/56630013/119958275-2d913e80-bfa3-11eb-91f5-aeafdaf989ab.png)

**Comment by MattBlissett** [comment]
> 1. Public network access, tested using the service on https://tools.gbif.org
>    Checking https://gbrds.gbif.org, http://rs.gbif.org should be enough to check public network access?
>    Or is the specific URL https://tools.gbif.org used in the code, and worth a check? (I can find references but not real calls)

Requests to https://gbrds.gbif.org and http://rs.gbif.org confirm there is outbound web access.  That's sufficient for fetching and updating DWC extension/vocabulary data, and registering datasets in GBIF's registry.

The other important thing is _inbound_ web access, so GBIF can retrieve the dataset after it's been registered.  In other words, checking the public URL / `baseURL` is correct, as is done on the initial IPT Setup II screen.  I hadn't realized, but this is only done in JavaScript at the moment: https://github.com/gbif/ipt/blob/master/src/main/webapp/WEB-INF/pages/admin/registration.ftl#L60-L83

> 2. I set a limit to 80% of disk usage, to display it in red. Do you agree?

Seems fine for me.

> 3. Is this page restricted or public?
> 4. Should we add a menu entry for this page?
> 5. Related to #3, I didn't display the real paths of the file permissions tests (config directory path, etc...), because we usually avoid to display publicly system information (to prevent attacks).

We already show file paths on /admin/config.do, which the admin can see.

We could either add this page to the Administration menu, or (maybe even better?) add the status to each option in the /admin/config.do page.  What do you think of something like this? (I just made it in developer tools.)

![Screen Shot 2021-05-29 at 12 14 49-fullpage](https://user-images.githubusercontent.com/583320/119969078-68e53a80-bfae-11eb-9bbc-ef5ca605dad0.png)

Or even changing the setup page to use the blocks.

**Comment by sylmorin-gbif** [comment]
1. Public access
I totally understand, so we need a 3rd party to check if our own IPT url is accessible.
It looks like https://tools.gbif.org/ws-validurl/?url=http://www.google.fr is doing that perfectly!

3.4.5. 
I understand your idea, but I think errors are less visible if the status is mixed with configuration.
Having the status on a dedicated page seems clearer for me.

What about having it public, without sensible information if you are not logged, like the paths and server information.

![image](https://user-images.githubusercontent.com/56630013/119994948-647c4a00-bfcd-11eb-9582-07b4f8d2bdd9.png)

And when logged:

![image](https://user-images.githubusercontent.com/56630013/119995041-7c53ce00-bfcd-11eb-9631-c005990a1b41.png)

(by the way, I added the application server info)

**Comment by MattBlissett** [comment]
> What about having it public, without sensible information if you are not logged, like the paths and server information.

This is also fine. Thanks for implementing it!

**Comment by sylmorin-gbif** [comment]
I created the PR https://github.com/gbif/ipt/pull/1584

**Comment by sylmorin-gbif** [comment]
I added an entry menu here, using font awesome icon:
![image](https://user-images.githubusercontent.com/56630013/120660061-3c865e00-c487-11eb-97f9-e393d366cb37.png)

It would be better to use the GBIF icon, wouldn't it? any plan to include them?

**Comment by mike-podolskiy90** [comment]
I ended up with the following UI:

![Screenshot 2021-06-08 at 22 29 06](https://user-images.githubusercontent.com/24795387/121254583-b7e27800-c8aa-11eb-80b0-4fa9ae71af2f.png)

@sylmorin-gbif thank you for all the work done!
I merged code into dev branch. Closing this.

**Comment by sylmorin-gbif** [comment]
Great ! 
I did plan to work on your remarks today but you were faster ! :) 

I like the GBIF icons for health and language buttons !
