### ISSUE TITLE
Received exception when trying to update change summary

### ISSUE THREAD

**Issue by amb26** [gbif/ipt#1658]
In attempting to edit the change summary for my materials, I received a blank page as shown ![change](https://user-images.githubusercontent.com/561418/134552846-720d1577-2fb7-4d18-9960-e6adb600bf82.png) with no editable fields. Trying to save it produced the following error:

````
The change summary for this version could not be updated. Please refresh the page and try again.

Oops
It seems you have discovered an unforeseen error:
````

There was no actual error text.

IPT version: Version 2.5.1-r8cce947

**Comment by mike-podolskiy90** [comment]
Thanks for reporting this issue @amb26 
It seems IPT failed to retrieve some important data for this form
Does this issue still persist?

**Comment by amb26** [comment]
Hi, I can easily provoke this error by attempting to edit the change summary message for a freshly submitted dataset. See enclosed image showing the UI state immediately before the error - to provoke the error, click on link "Edit" of dataset version 1.3.
![ipt-error-pre](https://user-images.githubusercontent.com/561418/135268438-dc9beb4f-79c7-4ab6-90a6-a7d6b106f88d.png)

**Comment by mike-podolskiy90** [comment]
Thanks for the details @amb26 

The problem is that you are trying to change the summary on the preview page which is read-only. We will remove those edit buttons.
If you want to change the summary for existing versions, please go to the Home tab. 
For the new version, the summary is populated when you click the Publish button on the resource overview page.

Hope this helps
