### ISSUE TITLE
Simple source file upload impossible with the French version of the IPT

### ISSUE THREAD

**Issue by SophiePamerlon** [gbif/ipt#1725]
Hi all,

I noticed a bug on v2.5.4 & 2.5.5 of the IPT during a training demo yesterday: when switched to French, once a resource is created, the upload of the source file or URL is not possible as the only option available for the three source choices (database, file, URL)  is database connection.

I managed to continue the demo by switching back to English, but the issue will certainly be problematic for French-speaking users that want to upload simple source files into their IPT.

Thank you!
Sophie

**Comment by sylmorin-gbif** [comment]
Not sure if it's related (but it could), but when we are on the manage resource page, we have a javascript error, due to ' character:

![image](https://user-images.githubusercontent.com/56630013/149299349-4775a8ba-f98a-4207-8cac-686137a07311.png)

How do we fix such issue?
For sure, we can use double quote in the code instead of simple quote.
But is there something easier to change in the i18n french file?

Thanks

**Comment by MattBlissett** [comment]
The other workaround would be using `’` rather than `'` in translations.

**Comment by ManonGros** [comment]
The same problem still exists for the Japanese version (we got an email on Helpdesk), could you fix it there is as well?

**Comment by mike-podolskiy90** [comment]
Thanks Marie, I'll fix that

**Comment by mike-podolskiy90** [comment]
This affects only registered resources

**Comment by mike-podolskiy90** [comment]
I deployed a fix to [UAT](ipt.gbif-uat.org)
