### ISSUE TITLE
IPT cannot properly delete a registered resource with DOI

### ISSUE THREAD

**Issue by mike-podolskiy90** [gbif/ipt#1737]
IPT displays the following messages on delete:
`Failed to remove resource`
`Registered DOI can't be deleted`
and resource remains active. 
But registry successfully deletes it, so it's shown as deleted on the portal.

**Comment by mike-podolskiy90** [comment]
related https://github.com/gbif/gbif-doi/issues/21

**Comment by MattBlissett** [comment]
https://ipt.gbif.org/manual/en/ipt/2.5/doi-workflow says what is supposed to happen ("Dataset publisher can choose to make dataset inaccessible; deactivates DOI; updates DOI metadata; resolves to landing page explaining dataset removed").

And also https://ipt.gbif.org/manual/en/ipt/2.5/versioning ("Deleted datasets have an IPT landing page that explains the dataset was removed. It the deleted dataset was assigned a DOI, all its versions are archived otherwise its permanently deleted.")
