### ISSUE TITLE
Admin UI management

### ISSUE THREAD

**Issue by mike-podolskiy90** [gbif/ipt#1814]
New functionality to simplify IPT UI customization.
Initial ideas:
- IPT logo upload
- IPT color schema management
- fonts management

**Comment by mike-podolskiy90** [comment]
This requires all styles quick revise to allow it simple customization

**Comment by peterdesmet** [comment]
For what it's worth, for my Jekyll website template [Petridish](http://peterdesmet.com/petridish/configuration/#colors--font), I allow users to customize:

- Colour of links (= Bootstrap primary colour)
- Colour of banner (= Bootstrap secondary colour)
- Colour of footer
- Font: serif/sans-serif
- Borders: rounded/not-rounded
- Logo

Especially the colours have a big effect (compare [this](https://globam.science/) with [this](https://oscibio.inbo.be/)), especially since they overwrite [Bootstrap variables](https://github.com/peterdesmet/petridish/blob/main/_sass/_variables.scss#L9-L11), and thus effect every element with that colour (e.g. buttons).

**Comment by mike-podolskiy90** [comment]
Thank you Peter for quick comments.
For now I extracted colors into variables that will be configurable:

- Base colors (primary, secondary, warning, danger)
- Navbar colors (navbar, navbar links)
- Links (regular, hover)
- Alerts (success, warning, danger)

There are some small issues to decide, like the banner "Test mode" which is not configurable right now.

**Comment by peterdesmet** [comment]
👍 I'd be careful in making too many colours customizable, as it can harm the user experience. Examples: allow customization of link colour, but use `darken()` for hoover, allow customization of navbar, but use `lighten()` or another function to make links stand out from the background. Alert colours (success, warning, danger) have a specific meaning and imo should not be customizable.
