### ISSUE TITLE
Dataset publication 'duplicate occurrenceID' message for non-duplicated occurrenceIDs

### ISSUE THREAD

**Issue by rukayaj** [gbif/ipt#1913]
I've got a published sampling event dataset which currently has 2 sets of occurrence & event source files from 2019 and 2020 see - https://ipt.gbif.no/resource?r=dnv. Every year I download new data from DNV's database, and then I have a script does some column mapping and arranges the data in event and occurrence sheets. I then upload these files to the IPT and publish them.

So, today I generated 2021's data as I did with the previous years and uploaded them - now the dataset has 2 372 473 records. But I get an error when I publish ([publication-log.log](https://github.com/gbif/ipt/files/10188730/publication-log.log)), saying that there are 30 duplicate occurrenceIDs. I am pretty sure this is not the case; the new occurrence file has uuids generated when I make the file in python/pandas.  

Stuff I've tried which hasn't shed any light on the matter:
- re-generating the 2021 data files (i.e. making new uuids)
- checking for duplicate occurrenceIDs in pandas against the other old files (i also forced them all lowercase on the offchance that was the problem)
- using  python to make [a csv of all the occurrenceIDs](https://drive.google.com/file/d/1bIzU5wPRRbrqUHzgJx3R0uJaFZmVyACB/view?usp=sharing) from the old and new files and then using other stuff to try find duplicates (excel and `sort all-occ-ids.csv | uniq -cd`, both said no duplicates) 
- adding a deliberate fake duplicate occurrenceID to the source file and checking pandas and `sort all-occ-ids.csv | uniq -cd` again to make sure I am not going insane :D
- publishing the old data on their own again without the new 2021 files (that was fine, so it is def something wrong with my new files, I just don't understand what) 

If anyone else is willing to look, here is [a zip of all three occurrence source files on the IPT server](https://drive.google.com/file/d/1lIHsI6GXJlESjYcmK7w4nK1eTxRHzWJm/view?usp=sharing). Here they are in the mapping:
<img width="886" alt="Screenshot 2022-12-08 at 21 27 26" src="https://user-images.githubusercontent.com/9654499/206551852-8f173438-be29-4ad6-8549-5c165152f0a0.png">
In the zip, `dnv-occurrences-2019.txt` is the same as `dnv-occurrences-updatedwithaphia.txt`, i just renamed it for the zip file so it's obvious what it is. I can also make anyone an acc on our IPT if that helps.

**Comment by mike-podolskiy90** [comment]
@rukayaj Thanks for reporting this, I'll have a look

**Comment by mike-podolskiy90** [comment]
@rukayaj I've checked your data and found the issue.
`"Thoracica Darwin, 1854"` - this scientific name causes problems in the result core file. Please make sure you have source's` Field Quotes` field set to `"`

**Comment by rukayaj** [comment]
That seems to have worked! Maybe it's worth adding something in the log files to ask people to check their field quotes? Anyway, thanks very much @mike-podolskiy90

**Comment by abubelinha** [comment]
@mike-podolskiy90 @rukayaj  I suspect I have this problem too when trying to provide a CSV file url data source (ipt.gbif-uat.org IPT Version 2.7.4-SNAPSHOT).

I have some questions concerning IPT source-data page:
>  **(pop-up informative message about "_field quotes_"):**
>
> A single character that encloses every field/column in a row. Most often empty, but CSV files use a ". 
> With this option, make sure that *all* of your fields are contained in quotes, not just those that are text. 
> Please note that in the IPT newline characters ( ) or carriage returns ( ) cannot be enclosed by quotes and should be removed.        
>Click in any of the following options:
>1. None 
>2. Double quote
>3. Single quote

- In my Google Chrome browser (Version 109.0.5414.120 Official Build 64-bit) I don't see the described characters (look empty `( )` above). And also, nothing happens when clicking in any of the options (the textbox remains empty).  Probably this is due to my old notebook which does not support Windows 10.  But I suspect typing `"` , `'` or `nothing` should have the same effect. Correct?
- I am a bit surprised/confused with the comment "_make sure that **all** of your fields are contained in quotes, not just those that are text_".  It was my understanding that quotes were only used to delimit values containing commas, to distinguish them from the usual separator commas.  
  So you mean fields that don't use to contain commas (like `occurrenceId`, `year` or `decimalLatitude`) should now be surrounded by quotes when we have filled in the "_field quotes_" textbox? (I don't recall needing to do so in the past).  
- With respect to removing carriage returns, is there any recommended way of doing that but still achieving the same visual effect?  Maybe we can replace them by `<br>` tags? 

@rukayaj any already tested recipes you can share on how to force pandas to do the last two things when using `.to_csv()` option?

Thanks!
@abubelinha

**Comment by rukayaj** [comment]
Hmm I think I did end up removing breaks as well, but it wasn't such a big issue in my data. I'm pretty sure I just did a .replace for them and put in a space instead, but I don't remember now I'm afraid. For the quotes I don't really remember what I did either, but https://pandas.pydata.org/docs/user_guide/io.html?highlight=csv%20quote_all possibly?
