### ISSUE TITLE
Allow copying metadata agents from any available resource

### ISSUE THREAD

**Issue by mike-podolskiy90** [gbif/ipt#1920]
Current option `Copy details from resource contact` is very limited - user can only copy the first contact from the same resource. It would be much more useful to be able to copy any agent from any resource available to the user.

**Comment by peterdesmet** [comment]
For what it's worth: since the functionality is currently so limited, I almost never use it. Never thought of needing it to copy agent information from _another_ resource. Personally, I would only revisit the need for this once #1166 is possible.

**Comment by mike-podolskiy90** [comment]
This can be useful if you need to add a new agent to many resources at the same time. New project personnel, for example

**Comment by albenson-usgs** [comment]
I like this idea! It would have been helpful to have when I was adding the [31 reef visual census datasets](https://www1.usgs.gov/obis-usa/ipt/?search=reef+visual) which had the exact same metadata, just different titles. When I added them there also wasn't the ability to load an EML file so that functionality probably would have helped too (I could have created the EML for one and then loaded that EML for the others, changing the title). This would help with mistakes that may happen from entering a person's information in multiple times, ensuring it's entered the same way every time.

**Comment by dbloom** [comment]
I concur. For those of us working with multiple resources from the same institution or organization, an option like this could be very helpful at times. Similarly, being able to select an enter metadata section (e.g.Project Data or Sampling Methods), instead of the entire EML file could be useful in the same way.
