### ISSUE TITLE
Cannot register new organization i IPT

### ISSUE THREAD

**Issue by DanBIF** [gbif/ipt#1996]
At danbif.au.dk I add [Herbarium of the University of Aarhus](https://www.gbif.org/publisher/8e1a97a0-3ca8-11d9-8439-b8a03c50a862) as a new organization. I enter the shared token copied from the registry. I save.
However, the org, does not appear on my IPT list of orgs. and I am not able to choose it on the liste of publishers when editing metadata of the dataset I wish to publish.
I am no getting any error message and couldn't find anything on the logs.

![image](https://user-images.githubusercontent.com/7815173/233087911-f0f00996-b34e-439d-b16c-0293bb15a21a.png)

**Comment by mike-podolskiy90** [comment]
Thanks for reporting, looking into it

**Comment by mike-podolskiy90** [comment]
Looks like the issue happens when browser auto-fill function is turned on. Browser for some reason fills in hidden fields (DOI related functionality). To prevent it from happening you can turn off auto-fill function, or select the checkbox "Associated with DOI registration agency", make sure nothing is auto-filled there (all fields empty) and unselect it.

Anyway, I managed to add association with Herbarium of the University of Aarhus to your IPT.

**Comment by DanBIF** [comment]
@mike-podolskiy90 Thank you very much for swift action. I did as explained and managed to make it work for me as well. Thank you for adding Herbarium of the University of Aarhus - we hope to publish tomorrow.
