### ISSUE TITLE
IPT fails to infer geographic scope metadata from source data

### ISSUE THREAD

**Issue by mike-podolskiy90** [gbif/ipt#2056]
Melissa Liu reported issues with the functionality.
![image](https://github.com/gbif/ipt/assets/24795387/29d284cb-10c5-463f-8e3a-62fbbd86d03e)

**Comment by peterdesmet** [comment]
@mike-podolskiy90 is this a general IPT issue or specific to an output format (DwC-A + EML, Frictionless)?

**Comment by mike-podolskiy90** [comment]
@peterdesmet Not sure. Users complained last week that they have issues with the functionality. Need to figure it out
@ManonGros Would be nice to have the source data/mappings and logs. Could you help please?

**Comment by ManonGros** [comment]
I have asked @melissa0520, apparently, since then the dataset has been deleted but she might have more examples

**Comment by ManonGros** [comment]
@mike-podolskiy90 could you check that dataset? https://training-ipt-b.gbif.org/manage/resource?r=melissa-test I think you should have access to that IPT

**Comment by mike-podolskiy90** [comment]
@ManonGros Thanks Marie, looking into it

**Comment by ymgan** [comment]
I encountered the same issue for all of the coverages (temporal, geographic and taxonomic) for a dataset that I just published. I made a copy to GBIF's test IPT so that you can have a look at: https://ipt.gbif.org/manage/resource.do?r=species-based-area-protection-in-antarctica 

I hope that helps! Thank you for your hard work!

![Screenshot 2023-06-30 at 10 26 00](https://github.com/gbif/ipt/assets/11754081/7763e65d-06c5-4ad3-9110-9db49b5b64bc)
![Screenshot 2023-06-30 at 10 25 46](https://github.com/gbif/ipt/assets/11754081/7d5903a3-9204-4ca4-a322-f85a7dd8578e)
![Screenshot 2023-06-30 at 10 25 21](https://github.com/gbif/ipt/assets/11754081/0b5ec439-db04-40c7-b2f7-c23e00c3a294)

**Comment by melissa0520** [comment]
@mike-podolskiy90 Could you tell me whats cause this issue? Thanks!

**Comment by mike-podolskiy90** [comment]
@melissa0520 Technical issues, internal types mismatch
