### ISSUE TITLE
New citation section and new fields for contributors

### ISSUE THREAD

**Issue by vechocho** [gbif/ipt#2087]
I'm running some test using the export from agouti.eu on a local IPT install.

What are the differences on the roles on the contributors? which ones are going to be listed as authors on the citation once the resource is registered on GBIF?

![image](https://github.com/gbif/ipt/assets/13081080/b77a9b53-78b3-42b8-b6c9-9cc788da7899)

**Comment by mike-podolskiy90** [comment]
Thank you for your questions.
@peterdesmet  I'm not sure if we already decided that?

**Comment by peterdesmet** [comment]
Indeed, that has not been decided yet. I am tempted to say all except `rightsHolder` and `contributor`.

@vechocho great to see you testing from Agouti! Note that Agouti is currently exporting data as Camtrap DP 0.6.0 while the IPT uses 1.0-rc.1, so mapping can be frustrating because of the differences. The work to update Agouti to Camtrap DP 1.0-rc.1 will start this week, so hopefully the descrepency will be resolved soon.

**Comment by vechocho** [comment]
Thank you @peterdesmet I'm trying with WildLife Insights too and have some mapping issues too. i just sent an email to the google group.

**Comment by vechocho** [comment]
I was trying with the test dataset that is on the CAMTRAP (MIKA) repository and I notice that the IPT publication doesn't generate an automated citation as it does for other resources, how is GBIF going to handle this once the recourse is registered ?

**Comment by peterdesmet** [comment]
I suggest the following:

1. Move `package.bibliographicCitation` and `package.references` out of `Other metadata` to a separate heading `Citations` just before that (cf. DwC-A)
2. As with DwC-A datasets, indicate that Free-text citations will be overwritten:

> Free-text citations get overwritten on the GBIF.org dataset page – learn more [here](https://www.gbif.org/faq?question=how-is-the-dataset-citation-text-auto-generated) and [here](https://www.gbif.org/faq?q=citation)

3. Add a button to enable/disable `Auto-generation` bibliographicCitation
4. When turned on, generate a citation as follows (cf. any convention used for DwC-A). Authors are the `{package.contributors}` with roles `contributor`, `contact` and `principalInvestigator` (leaving out `publisher` and `rightsHolder`) in the order provided in `Basic Metadata` (cf. DwC-A). Duplicates (same `title`) are removed.

> {package.contributors} ({year}). {package title}. Version {ipt resource version}. {registered publisher}. Dataset. {package.id}

5. When turned off, allow free text.

Questions:

1. How to parse the contributor `title` into first name/last name?
2. When uploading a `datapackage.json` that contains a `bibliographicCitation`, should it be ignored if auto-generation is turned on? Or should auto-generation be turned off?
3. Should contributor(s) with role `publisher` be ignored when uploading a `datapackage.json`? I would argue yes, as it can conflict with the registered GBIF publisher
4. Should contributor(s) with role `rightsHolder` be ignored when uploading a `datapackage.json`? I would argue no, as it can is used for the Darwin Core mapping later on. This contributor should be ignored for the citation though.

**Comment by mike-podolskiy90** [comment]
@peterdesmet Thank you Peter.

1. We can't properly parse title. The only idea I have right now add two more fields to the contributor model, or keep them somewhere else (something like `gbif` in EML).

2. I think on upload we need to add a modal confirmation window.

**Comment by mike-podolskiy90** [comment]
Citation looks like this now:
```
 (2024). camtrap-stuff. Version 1.0. Camtrap-dp dataset. http://localhost:8080/resource?r=camtrap-stuff&amp;v=1.0
```

Is it fine? I guess it should be `Camtrap dataset` or `Camtrap DP dataset`

**Comment by mike-podolskiy90** [comment]
> 3. Should contributor(s) with role publisher be ignored when uploading a datapackage.json? I would argue yes, as it can conflict with the registered GBIF publisher
> 4. Should contributor(s) with role rightsHolder be ignored when uploading a datapackage.json? I would argue no, as it can is used for the Darwin Core mapping later on. This contributor should be ignored for the citation though.

Ignored you mean not included in the citation?

**Comment by peterdesmet** [comment]
I propose the following.

## For contributors with role `publisher` and `rightsHolder`

- Exclude from citation
- Can be persons or organizations, but we only need the `title` property
- Show the following form (current implementation):

<img width="887" alt="Screenshot 2024-01-09 at 15 49 46" src="https://github.com/gbif/ipt/assets/600993/9932f62e-409b-4337-90c9-5100c16accb1">

## For other contributors

These are contributors with role `contributor`, `contact`, `principleInvestigator` or without a role (e.g. when creating a new contributor).

- Include in citation
- Need to be persons (this is a reasonable assumption)
- Need to have a `firstName` and `lastName` (for the citation) in addition to `title` (which is a required field). All three properties are saved in the `datapackage.json`. `title` cannot be edited by the user.
- Show the following form:

<img width="879" alt="Screenshot 2024-01-09 at 15 55 23" src="https://github.com/gbif/ipt/assets/600993/f50ad26c-75ab-4426-84f4-76c4cb1e26b5">

- When **importing** data and no `firstName`/`lastName` is present (for these types of contributors), the IPT will guess `firstName`/`lastName` by splitting `title` on the first space (`Abel De Boer` -> `Abel`, `De Boer`).
- If the `title` consist of a single word, only `firstName` is populated. Since it is a required field, an error will be shown when trying to save metadata.
- When saving the Basic Metadata page, all `title`s are regenerated from `firstName lastName`. Ideally this could also be done directly when the user is typing in `firstName` or `lastName`.
- When the `role` is switched between the two types of contributors, the form changes.

## Citation

I agree with the citation, and would use `Camtrap DP dataset`. I think it makes sense to also include the registered publisher (note that for DwC-A, this is currently shown _before_ the type of dataset. Might want to align that).

> Last F, Last F, Last F(2024). camtrap-stuff. Version 1.0. Camtrap DP dataset. Research Institute for Nature and Forest (INBO). http://localhost:8080/resource?r=camtrap-stuff&amp;v=1.0

**Comment by mike-podolskiy90** [comment]
@peterdesmet I've deployed the first version to IPT3 UAT

**Comment by mike-podolskiy90** [comment]
CItation is different on the portal though. We currently convert to Occurrence dataset so it's displayed like that https://www.gbif-uat.org/dataset/a64520de-0b98-466f-bfb9-00219ad6697b

```
Test Organization #1. MICA - Full dataset. Occurrence dataset https://doi.org/10.21373/p2xwn2 accessed via GBIF.org on 2024-01-18.
```

**Comment by peterdesmet** [comment]
> CItation is different on the portal though.

Is there a possibility to build the citation with authors, cf. datasets with EML?

**Comment by mike-podolskiy90** [comment]
Yes, titles disappeared, looking into that.

**Comment by mike-podolskiy90** [comment]
I need to refresh my memory how we deal with the citation in the GBIF registry

**Comment by mike-podolskiy90** [comment]
@peterdesmet I believe titles and names should be fine now.

**Comment by peterdesmet** [comment]
I have uploaded a datapackage.json now and the first and last names are automatically parsed. However:

1. The names are currently not parsed on the first word as suggested in https://github.com/gbif/ipt/issues/2087#issuecomment-1883249674, so `Danny Van der beeck` becomes first: `Danny Van der` and last `beeck`. Multiple first names can happen too, but I think multiple last names might be more common, so I would still split on the first word.
2. When uploading, the dialog box warns that auto-citation is turned on, even when it is not. It _does_ overwrite the bibliographicCitation (and sets it empty).

<img width="448" alt="Screenshot 2024-01-24 at 16 00 12" src="https://github.com/gbif/ipt/assets/600993/3a909ebd-ca67-4db5-ad26-2fd0a3e5d848">

3. When changing a contributor to publisher/rightsHolder, the title is retained 👍 . However, when (saving and) changing back to a contributor, the title is retained, but first and last name are not created. If you then forget to populate those fields and save, the page returns an error and the title is empty as well. Not sure how to prevent this, unless first/lastName are also created when switching roles.

**Comment by mike-podolskiy90** [comment]
Thanks Peter, looking into that

**Comment by peterdesmet** [comment]
All issues I mentioned are resolved, thanks!
