### ISSUE TITLE
coordinatePrecision field for the geographic scope metadata

### ISSUE THREAD

**Issue by mike-podolskiy90** [gbif/ipt#2130]
Currently it's only stored in the metadata. Should be applied to the coordinates

**Comment by peterdesmet** [comment]
Do you mean that when setting a `coordinatePrecision` in the metadata, all coordinates in the data should be rounded to that precision when creating the package? I think that would be a nice feature, but I think it should be optional.

**Comment by mike-podolskiy90** [comment]
I mean if we automatically infer the metadata we should consider this field? Otherwise it does not make sense

**Comment by peterdesmet** [comment]
Do you mean in the other direction then? Derive the metadata's `coordinatePrecision` from the data? The definition of the field is here: https://camtrap-dp.tdwg.org/metadata/#coordinatePrecision and it is optional. It's main purpose is to indicate to users _if_ and by how much coordinates in the data have been rounded.

**Comment by mike-podolskiy90** [comment]
Okay, I think I see. So should we infer that?

**Comment by peterdesmet** [comment]
I'm not entirely sure yet how users will use this feature and what their expectations are. I personally wouldn't infer the `coordinatePrecision` from the least number of decimals in the data, since a precise `51.400` can be expressed as `51.4` in the data. If it is inferred, users should always have the option to override the value.

I think the following features would be useful, but implementation is optional:

1. Only retain `coordinatePrecision` if it was included in an uploaded `datapackage.json`. Don't include the property otherwise.
2. Have a `coordinatePrecision` field controlled by the user (`empty`, `0.00001`, `0.0001`, `0.001`, `0.01`, `0.1`, `1`). It would be the only value the user can control in geospatial scope. The field can also be moved to another section as it isn't necessarily part of the geospatial scope.
3. Have a `coordinatePrecision` field controlled by the user (as above). Offer the option to round all coordinates in the data to that precision upon publication.

**Comment by mike-podolskiy90** [comment]
Thanks. I think we can start with the first implementation. Users can have it if they upload a metadata file with the field.
