### ISSUE TITLE
Open Definition License support for Camtrap DP

### ISSUE THREAD

**Issue by mike-podolskiy90** [gbif/ipt#2186]
Camtrap DP supports [Open Definition License](https://licenses.opendefinition.org/licenses/groups/all.json) for the media and data licenses.

On the other hand, GBIF supports only creative commons licenses (CC0, CC-BY, CC-BY-NC).

There are two possible solutions:

1. Restrict the data license to those three we support. The media license can be any.
2. Any license for both media and data. But if user wants to register a dataset in GBIF, then they must assign a license supported by GBIF.

@timrobertson100

**Comment by timrobertson100** [comment]
Thanks @mike-podolskiy90 

My inclination would be to keep the IPT compliant with the GBIF network decisions. I'm not sure I would anticipate users dealing with CamtrapDP datasets aiming for anything other than publishing to GBIF when using the IPT.

**Comment by peterdesmet** [comment]
I agree, the IPT can set more restrictions when publishing a Camtrap DP, so restricting `license > data` to the 3 allowed by GBIF is fine.

I only hesitate a bit about restricting the license for the media to the three options, since media files are not covered by the IPT license restrictions. But I also don't think users would object to having their choses restricted to those 3 for media files.

**Comment by mike-podolskiy90** [comment]
OK. So the data license remains restricted to three GBIF ones. The media license can be any Open Definition one.

**Comment by peterdesmet** [comment]
> The media license can be any Open Definition one.

Would this be presented as a dropdown to the user? Because that would be my preference (and then I'm personally fine with restricting it to the 3 GBIF licenses).

**Comment by mike-podolskiy90** [comment]
Yes, it would

**Comment by mike-podolskiy90** [comment]
Deployed to UAT

**Comment by mike-podolskiy90** [comment]
Re-deployed a fixed version to UAT

**Comment by peterdesmet** [comment]
- [ ] Since the dropdown of potential licenses is quite long: could the UI of the dropdown by changed to a **search** and dropdown. Cf. the one used for mapping terms:

<img width="400" alt="Screenshot 2023-11-10 at 14 36 55" src="https://github.com/gbif/ipt/assets/600993/a004deab-b5e4-47c6-9ba4-9f43c52ee43b">


- [ ] Media license is indicated as required term in the IPT. However, when uploading a datapackage.json without a (matching) media license, the resource page showed the metadata as complete:
<img width="889" alt="Screenshot 2023-11-10 at 14 33 02" src="https://github.com/gbif/ipt/assets/600993/757f5e56-34ba-41ee-90c6-b2cd2f5f6b7d">

**Comment by mike-podolskiy90** [comment]
Thanks, I'll add a search feature.
Looks like something needs to be adjusted in the validation

**Comment by mike-podolskiy90** [comment]
Deployed to UAT

**Comment by peterdesmet** [comment]
Tested.
