### ISSUE TITLE
Version numeration for new Data Packages

### ISSUE THREAD

**Issue by EstebanMH-SiB** [gbif/ipt#2293]
All new versions for the new data packages go in integers 1.0, 2.0, 3.0, etc:
<img width="435" alt="image" src="https://github.com/gbif/ipt/assets/63795703/fa3af44a-f499-4211-bc36-a76c66f0e165">

Rather than in a decimal way 1.0,  1.1, 1.2, etc as is done in previous datasets, unless that you choose that is a new major version:
<img width="511" alt="image" src="https://github.com/gbif/ipt/assets/63795703/05604509-ff0c-4ca2-9597-2b1e09702262">

I was wondering if this is on purpose or we should keep the same style of numbering for new versions, regardless of data package or traditional cores.

Thanks in advance and sorry if this has already been addressed,

**Comment by mike-podolskiy90** [comment]
Thank you for contacting us. If I remember correctly that was intentional @peterdesmet

**Comment by peterdesmet** [comment]
Indeed, the change was intentional, but **likely needs a larger discussion**.

Personally I'm not a fan of the current semantic minor/major versioning for dataset in the IPT:

1. Currently publishers of DwC-A are prompted:

    > You are about to publish a new minor version of this resource. If there have been scientifically significant changes to the resource since the last publication, you should cancel, assign this resource a new DOI, and then publish again.

    But it is **unclear what are significant changes** + when your DOI is not minting DOIs, you **cannot create a major version**.

2. The version number is not retained on GBIF dataset pages. I don't know how DOI changes for a new major version of a resource are handled.

I would opt for a simpler versioning, similar to what Zenodo uses:

1. Default versioning is `v1`, `v2`, `v3` (see https://zenodo.org/records/10053903), rather than `1.1`, `1.2`, `1.3` currently used for DwC-A and the `1.0`, `2.0`, `3.0` currently used for Data Packages. This is fairly easy to understand and doesn't hint at major/minor versions.
2. Optionally: users can define their own version number (e.g. to refer to a specific versioning system they use elsewhere for their dataset).
3. The version number is (still) not displayed at GBIF dataset pages.
4. DOI changes are not directly linked to a major version number change.

**Comment by mike-podolskiy90** [comment]
Yes, versioning like `v1` seems more reasonable to me.

**Comment by EstebanMH-SiB** [comment]
Thanks for your input, we agree that v1, v2, etc versioning is the best way going forward, for datapackages and traditional resources alike

**Comment by mike-podolskiy90** [comment]
@peterdesmet I think we should include it in the release

**Comment by mike-podolskiy90** [comment]
With `v1` `v2` `v3` versioning we don't need to store the `v` letter itself in the `resource.xml` file? I think number would be enough

**Comment by peterdesmet** [comment]
Yes, I think the number is enough in `resource.xml` (`2` for `v2` in the UI).

**Comment by mike-podolskiy90** [comment]
deployed to UAT
