### ISSUE TITLE
Associate a Camtrap DP resource with an existing GBIF dataset

### ISSUE THREAD

**Issue by mike-podolskiy90** [gbif/ipt#2434]
For DwC resources this can be done by adding a GBIF UUID to `Alternative Identifiers`. Currently, it's not possible for Camtrap DP resources.

Discussed with @peterdesmet @ManonGros

**Comment by mike-podolskiy90** [comment]
We bind an IPT resource with a GBIF dataset by GBIF UUID. So, we can do something similar for Camtrap resources:

![Screenshot 2024-06-01 at 18 54 51](https://github.com/gbif/ipt/assets/24795387/a3858d54-b3c8-4bbc-8187-73f77d82512e)

`Related Identifier` should be a dataset page at the GBIF portal and `Related Identifier type` should be `URL`. `Relation type` can be anything I think.

@peterdesmet If you're fine with that I can release it next week

**Comment by peterdesmet** [comment]
Tested and works in the IPT: got a notification on registering that it will be linked to an existing resource. Haven't been able to fully test how harvesting is affected on UAT.

**Comment by peterdesmet** [comment]
Here are the steps for anyone else who wants to **replace** a Darwin Core Archive `resource A` with a Camtrap DP `resource B` version:

1. Create `resource A` (a DwC-A version of a camera trap dataset) at shortname `resource-a`
2. Publish `resource A`
3. Register `resource A` => Dataset page `Page A` on GBIF
4. Create `resource B` (a Camtrap DP version of the same dataset) at shortname `resource-b` (the shortname will thus not be retained, unless you delete `resource A` first)
5. Add `relatedIdentifier` to `resource B` as described [above](https://github.com/gbif/ipt/issues/2434#issuecomment-2143513555) pointing to `Page A`
6. Delete `resource A`. When asked, choose `IPT only (orphan)`. It won't disappear from the list of resources because of bug #2248
7. Publish `resource B`
8. Register `resource B`
9. Wait and verify `Page A` now shows information for `resource B`
10. Optional: remove `relatedIdentifier` from `resource B`, as it is no longer needed.

**Comment by mike-podolskiy90** [comment]
This is fixed on the IPT side. 
More crawler work is needed https://github.com/gbif/crawler/issues/68

**Comment by mike-podolskiy90** [comment]
This should be added to the GBIF IPT manual
