### ISSUE TITLE
Source file via URL

### ISSUE THREAD

**Issue by kbraak** [gbif/ipt#790]
```
What feature would like to see being added to the IPT?
Currently you can get source data by uploading a file or connecting a database.

I would find it very useful if I could link to a source file via a public URL. That
way I don't have to 1) remember the URL, as it is stored by IPT; 2) download and upload
each time a new version of the file  is available. This would be very useful for hosted
IPT setups.

It should be possible to 1) manually refresh the connection, so a new version of the
file is uploaded by IPT; 2) alter the URL in case it has changed.
```

Original issue reported on code.google.com by `Peter.Desmet` on 2011-10-01 04:11:06

**Comment by MattBlissett** [comment]
Could this work with some creative JDBC parameters, using something like http://csvjdbc.sourceforge.net/ ?  Hmm, https://github.com/jprante/jdbc-driver-csv (a fork) gives more information, only simple SELECT is supported, with no joins.

Perhaps HSQLDB Text Tables: http://hsqldb.org/doc/2.0/guide/texttables-chapt.html

**Comment by peterdesmet** [comment]
Revisiting this issue: I still think connecting to source data via URL would be very useful. But instead of manually uploading the file to the IPT via the stored URL (as originally described), I think it would be more convenient if IPT can do this automatically on mapping or publication, similar to a DB connection.

**Comment by pieterprovoost** [comment]
A bit late to the party but I support this proposal. This would be very helpful to do some automation without having to set up a database, mess with the data directory, or automate browser actions with Selenium (yes, that happens). An S3 connector would work as well.

**Comment by peterdesmet** [comment]
This feature would be really helpful for a new project we have started, to allow rapid and repeated publication of invasive species data to GBIF. It would allow data publishers to host their (updated) data at a public URL and then use IPT's **auto publishing** feature to publish those data regularly to GBIF.

Currently, the auto publication feature does not make much sense for files, since you still have to manually upload them. It only make sense for database connections, but that either requires an open database port over the internet (which many data providers do not want to do for security reasons) or to host an IPT close to the database (which many data providers don't want to maintain). Allow the IPT to pull source files from an URL would solve that.

Could this feature be included in an early release of the [2.5.x track](https://github.com/gbif/ipt/milestone/27), please?

**Comment by timrobertson100** [comment]
Thanks @peterdesmet @pieterprovoost 

We are shortly going to be triaging the 2.5.x issues, and it seems wholly reasonable to include this as a priority.

**Comment by peterdesmet** [comment]
Please make this part of 2.5 if it is not so already. 🙏

**Comment by MattBlissett** [comment]
@peterdesmet, Mikhail has implemented this.  It's part of this snapshot if you'd like to make a quick test: https://repository.gbif.org/repository/snapshots/org/gbif/ipt/2.5.0-RC2-SNAPSHOT/ipt-2.5.0-RC2-20210819.133619-98.war 

Also https://ipt.gbif-uat.org/manual/en/ipt/2.5/manage-resources#url-as-data-source

**Comment by peterdesmet** [comment]
Excellent! I can't make a quick test right now, but nice to see this implemented. Question:

> The IPT can import uncompressed delimited text files [...] directly from a URL.

Does this mean that compressed delimited text files are not supported? If so, why?

**Comment by mike-podolskiy90** [comment]
@peterdesmet Yes, compressed files are not supported in the 2.5.0. We will consider supporting them in the next versions.

**Comment by abubelinha** [comment]
Could someone tell me if using an URL data source has any effect on saving IPT disk space when compared to using file upload or remote database data sources?
I understand there is no difference between the three options, since the IPT will store a zipped DwC-A anyway. 

And for the same reason, using zipped or plain text csv files make no differences regarding IPT disk usage (that only affects uploading/downloading times, and also remote server disk usage in case of URL data sources).

Am I right?
Thanks

**Comment by mike-podolskiy90** [comment]
@abubelinha Thank you for your questions.
File sources - IPT stores files inside; URL - IPT does not store data itself, only URL and reads it every time when needed.

**Comment by abubelinha** [comment]
Thanks @mike-podolskiy90 
So indeed that makes a difference in IPT disk usage.

As for the URL, I understand it doesn't hurt if it is deleted after having successfully published the dataset? (as far as we don't try to publish again -either manual or autopublish- from the same datasource).

**Comment by mike-podolskiy90** [comment]
@abubelinha correct
