### ISSUE TITLE
On manage resource page, allow metadata to be populated via uploaded EML file

### ISSUE THREAD

**Issue by kbraak** [gbif/ipt#955]
```
as per title

What version of the provider software are you using?
Version 2.0.4

```

Original issue reported on code.google.com by `kyle.braak` on 2013-03-19 14:24:08

**Comment by meliezer** [comment]
As Kyle has replied to an identical issue: You can also create a new resource using only the metadata file. For instructions, see this section of the user manual: https://github.com/gbif/ipt/wiki/IPT2ManualNotes.wiki#upload-a-metadata-file
I'm adding that this work-around is very good, since one can easliy change the resource to evet/occurrence core based resource.

Regards,
Menashè

**Comment by meliezer** [comment]
Cool! Thank you!
